## Data Reading

### CSV Files

In [64]:
import os
import sys

# Force the kernel to use your Homebrew Java 17 path
os.environ["JAVA_HOME"] = (
    "/opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home"
)

# Tell PySpark exactly which Python executable to target (prevents system mismatches)
os.environ["PYSPARK_PYTHON"] = sys.executable
os.environ["PYSPARK_DRIVER_PYTHON"] = sys.executable

In [65]:
from pyspark.sql import SparkSession

In [66]:
spark = SparkSession.builder.appName("Citibike Analysis").getOrCreate()

In [67]:
main_schema = """
    ride_id string, 
    rideable_type string,
    started_at timestamp,
    ended_at timestamp,
    start_station_name string, 
    start_station_id string,
    end_station_name string,
    end_station_id string,
    start_lat double,
    start_lng double,
    end_lat double,
    end_lng double,
    member_casual string
"""

trips = (
    spark.read.format("csv")
    .schema(main_schema)
    .option("header", True)
    .load("/Users/pius/Projects/analytics-engineering/Spark/data/JC*.csv")
)

26/07/02 10:21:52 WARN FileStreamSink: Assume no metadata directory. Error while looking for metadata directory in the path: /Users/pius/Projects/analytics-engineering/Spark/data/JC*.csv.
java.io.FileNotFoundException: File /Users/pius/Projects/analytics-engineering/Spark/data/JC*.csv does not exist
	at org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileStatus(RawLocalFileSystem.java:980)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatusInternal(RawLocalFileSystem.java:1301)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:970)
	at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:462)
	at org.apache.spark.sql.execution.streaming.sinks.FileStreamSink$.hasMetadata(FileStreamSink.scala:58)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:384)
	at org.apache.spark.sql.catalyst.analysis.ResolveDataSource.org$apache$spark$sql$catalyst$analysis$ResolveDataSource$$loadV1BatchSource(ResolveDataSource.scala:143)
	at org.apache.spark.sql.catalyst.analysis.ResolveDataSource$$anonfun$apply$1.$anonfun$applyOrElse$2(ResolveDataSource.scala:61)
	at scala.Option.getOrElse(Option.scala:201)
	at org.apache.spark.sql.catalyst.analysis.ResolveDataSource$$anonfun$apply$1.applyOrElse(ResolveDataSource.scala:61)
	at org.apache.spark.sql.catalyst.analysis.ResolveDataSource$$anonfun$apply$1.applyOrElse(ResolveDataSource.scala:45)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUpWithPruning$3(AnalysisHelper.scala:139)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(origin.scala:107)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUpWithPruning$1(AnalysisHelper.scala:139)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:416)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUpWithPruning(AnalysisHelper.scala:135)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUpWithPruning$(AnalysisHelper.scala:131)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsUpWithPruning(LogicalPlan.scala:37)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUp(AnalysisHelper.scala:112)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUp$(AnalysisHelper.scala:111)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsUp(LogicalPlan.scala:37)
	at org.apache.spark.sql.catalyst.analysis.ResolveDataSource.apply(ResolveDataSource.scala:45)
	at org.apache.spark.sql.catalyst.analysis.ResolveDataSource.apply(ResolveDataSource.scala:43)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$2(RuleExecutor.scala:248)
	at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:183)
	at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:179)
	at scala.collection.immutable.List.foldLeft(List.scala:79)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1(RuleExecutor.scala:245)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1$adapted(RuleExecutor.scala:237)
	at scala.collection.immutable.List.foreach(List.scala:323)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:237)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.org$apache$spark$sql$catalyst$analysis$Analyzer$$executeSameContext(Analyzer.scala:343)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$execute$1(Analyzer.scala:339)
	at org.apache.spark.sql.catalyst.analysis.AnalysisContext$.withNewAnalysisContext(Analyzer.scala:224)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:339)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:289)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$executeAndTrack$1(RuleExecutor.scala:207)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:89)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.executeAndTrack(RuleExecutor.scala:207)
	at org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.resolveInFixedPoint(HybridAnalyzer.scala:236)
	at org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.$anonfun$apply$1(HybridAnalyzer.scala:91)
	at org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.withTrackedAnalyzerBridgeState(HybridAnalyzer.scala:122)
	at org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.apply(HybridAnalyzer.scala:84)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:322)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:423)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:322)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$lazyAnalyzed$2(QueryExecution.scala:139)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:148)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$2(QueryExecution.scala:330)
	at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:717)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:330)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:804)
	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:329)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$lazyAnalyzed$1(QueryExecution.scala:139)
	at scala.util.Try$.apply(Try.scala:217)
	at org.apache.spark.util.Utils$.doTryWithCallerStacktrace(Utils.scala:1392)
	at org.apache.spark.util.LazyTry.tryT$lzycompute(LazyTry.scala:46)
	at org.apache.spark.util.LazyTry.tryT(LazyTry.scala:46)
	at org.apache.spark.util.LazyTry.get(LazyTry.scala:58)
	at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:150)
	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:90)
	at org.apache.spark.sql.classic.Dataset$.$anonfun$ofRows$1(Dataset.scala:114)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:804)
	at org.apache.spark.sql.classic.Dataset$.ofRows(Dataset.scala:112)
	at org.apache.spark.sql.classic.DataFrameReader.load(DataFrameReader.scala:108)
	at org.apache.spark.sql.classic.DataFrameReader.load(DataFrameReader.scala:99)
	at org.apache.spark.sql.classic.DataFrameReader.load(DataFrameReader.scala:57)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:184)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:108)
	at java.base/java.lang.Thread.run(Thread.java:840)

In [68]:
print(f"Total rows loaded: {trips.count()}")

Total rows loaded: 4700530

In [69]:
# Or

# trips = spark.read.csv(
#     "/home/piusm/dev-projects/analytics-engineering/Spark/data/JC*.csv",
#     inferSchema=True,
#     header=True,
# )

#### Alternative way of defining a schema

In [70]:
# my_struct_schema = StructType(
#     [
#         StructField("ride_id", StringType(), True),
#         StructField("rideable_type", StringType(), True),
#         StructField("started_at", TimestampType(), True),
#         StructField("ended_at", TimestampType(), True),
#         StructField("start_station_name", StringType(), True),
#         StructField("start_station_id", StringType(), False),
#         StructField("end_station_name", StringType(), True),
#         StructField("end_station_id", StringType(), True),
#         StructField("start_lat", DoubleType(), True),
#         StructField("start_lng", DoubleType(), True),
#         StructField("end_lat", DoubleType(), True),
#         StructField("end_lng", DoubleType(), True),
#         StructField("member_casual", StringType(), True),
#     ]
# )

In [71]:
trips.show()

+----------------+-------------+--------------------+--------------------+--------------------+----------------+--------------------+--------------+-----------------+------------------+-----------------+------------------+-------------+
|         ride_id|rideable_type|          started_at|            ended_at|  start_station_name|start_station_id|    end_station_name|end_station_id|        start_lat|         start_lng|          end_lat|           end_lng|member_casual|
+----------------+-------------+--------------------+--------------------+--------------------+----------------+--------------------+--------------+-----------------+------------------+-----------------+------------------+-------------+
|172DBBFC733F03CE|electric_bike|2024-10-10 14:54:...|2024-10-10 15:04:...|         Oakland Ave|           JC022|Stevens - River T...|         HB602|       40.7376037|       -74.0524783|40.74313282710551|-74.02698867022991|       member|
|D20BBA4860FE736C|electric_bike|2024-10-03 19:20:...|2024-10-03 19:31:...|         Oakland Ave|           JC022|Stevens - River T...|         HB602|       40.7376037|       -74.0524783|40.74313282710551|-74.02698867022991|       casual|
|86F89348995D0E6E| classic_bike|2024-10-20 12:14:...|2024-10-20 12:28:...|         Oakland Ave|           JC022|South Waterfront ...|         HB103|       40.7376037|       -74.0524783|40.73698221818716|-74.02778059244156|       casual|
|AA55A717B7EC1D10| classic_bike|2024-10-20 14:40:...|2024-10-20 14:55:...|         Oakland Ave|           JC022|      Columbus Drive|         JC014|       40.7376037|       -74.0524783|40.71835519823214|-74.03891444206238|       member|
|C72953D91E986DA7| classic_bike|2024-10-20 08:37:...|2024-10-20 08:42:...|     Brunswick & 6th|           JC081|       Washington St|         JC098|40.72601172964625|-74.05038893222809|       40.7242941|       -74.0354826|       member|
|23A1827EA03A9AC2|electric_bike|2024-10-28 19:20:...|2024-10-28 19:25:...|         Oakland Ave|           JC022|Hoboken Ave at Mo...|         JC105|       40.7376037|       -74.0524783|40.73520838045357|-74.04696375131607|       member|
|6C0E882AE20AC640|electric_bike|2024-10-08 10:41:...|2024-10-08 10:44:...|      Pershing Field|           JC024| Leonard Gordon Park|         JC080|     40.742677141|     -74.051788633|40.74590996631558| -74.0572714805603|       member|
|FC4AEE485D39016D|electric_bike|2024-10-25 21:02:...|2024-10-25 21:11:...|      Pershing Field|           JC024| Leonard Gordon Park|         JC080|     40.742677141|     -74.051788633|40.74590996631558| -74.0572714805603|       member|
|3E4D96936A8660C6|electric_bike|2024-10-08 12:17:...|2024-10-08 12:20:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|
|9F2FBA8132468A3B|electric_bike|2024-10-28 11:00:...|2024-10-28 11:03:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|
|B71B07C28733404F|electric_bike|2024-10-26 11:39:...|2024-10-26 11:45:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|
|2EE1AB7AFEFB4CBB| classic_bike|2024-10-02 23:43:...|2024-10-02 23:47:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|
|A7493DA7AFDDBC44| classic_bike|2024-10-12 12:48:...|2024-10-12 13:16:...|         Exchange Pl|           JC116|Stevens - River T...|         HB602|40.71636596185077|  -74.034343957901|40.74313282710551|-74.02698867022991|       member|
|7A956542D29EA30E| classic_bike|2024-10-24 17:48:...|2024-10-24 17:53:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|
|157EFB12EA94DA9A|electric_bike|2024-10-02 14:37:...|2024-10-02 14:41:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|
|3A54C7F77E03FB73| classic_bike|2024-10-06 01:42:...|2024-10-06 01:48:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|
|94374385A5951BEE| classic_bike|2024-10-22 16:38:...|2024-10-22 16:45:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|
|5E9040B2EF62AE11|electric_bike|2024-10-21 13:45:...|2024-10-21 13:57:...|      Pershing Field|           JC024|Stevens - River T...|         HB602|     40.742677141|     -74.051788633|40.74313282710551|-74.02698867022991|       member|
|99D204D580A9BD0C|electric_bike|2024-10-07 13:39:...|2024-10-07 13:48:...|      Pershing Field|           JC024|Stevens - River T...|         HB602|     40.742677141|     -74.051788633|40.74313282710551|-74.02698867022991|       member|
|7C3E2DA95C52FDFB|electric_bike|2024-10-03 08:52:...|2024-10-03 09:02:...|      Pershing Field|           JC024|Stevens - River T...|         HB602|     40.742677141|     -74.051788633|40.74313282710551|-74.02698867022991|       member|
+----------------+-------------+--------------------+--------------------+--------------------+----------------+--------------------+--------------+-----------------+------------------+-----------------+------------------+-------------+
only showing top 20 rows

In [72]:
trips.count()

4700530

In [73]:
trips.limit(10).toPandas()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,172DBBFC733F03CE,electric_bike,2024-10-10 14:54:24.572,2024-10-10 15:04:07.657,Oakland Ave,JC022,Stevens - River Ter & 6 St,HB602,40.737604,-74.052478,40.743133,-74.026989,member
1,D20BBA4860FE736C,electric_bike,2024-10-03 19:20:21.215,2024-10-03 19:31:46.511,Oakland Ave,JC022,Stevens - River Ter & 6 St,HB602,40.737604,-74.052478,40.743133,-74.026989,casual
2,86F89348995D0E6E,classic_bike,2024-10-20 12:14:56.318,2024-10-20 12:28:32.053,Oakland Ave,JC022,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,40.737604,-74.052478,40.736982,-74.027781,casual
3,AA55A717B7EC1D10,classic_bike,2024-10-20 14:40:15.227,2024-10-20 14:55:39.100,Oakland Ave,JC022,Columbus Drive,JC014,40.737604,-74.052478,40.718355,-74.038914,member
4,C72953D91E986DA7,classic_bike,2024-10-20 08:37:03.280,2024-10-20 08:42:24.770,Brunswick & 6th,JC081,Washington St,JC098,40.726012,-74.050389,40.724294,-74.035483,member
5,23A1827EA03A9AC2,electric_bike,2024-10-28 19:20:28.668,2024-10-28 19:25:28.448,Oakland Ave,JC022,Hoboken Ave at Monmouth St,JC105,40.737604,-74.052478,40.735208,-74.046964,member
6,6C0E882AE20AC640,electric_bike,2024-10-08 10:41:37.926,2024-10-08 10:44:23.533,Pershing Field,JC024,Leonard Gordon Park,JC080,40.742677,-74.051789,40.745910,-74.057271,member
7,FC4AEE485D39016D,electric_bike,2024-10-25 21:02:40.878,2024-10-25 21:11:00.117,Pershing Field,JC024,Leonard Gordon Park,JC080,40.742677,-74.051789,40.745910,-74.057271,member
8,3E4D96936A8660C6,electric_bike,2024-10-08 12:17:23.948,2024-10-08 12:20:47.035,City Hall - Washington St & 1 St,HB105,Stevens - River Ter & 6 St,HB602,40.737360,-74.030970,40.743133,-74.026989,member
9,9F2FBA8132468A3B,electric_bike,2024-10-28 11:00:40.004,2024-10-28 11:03:12.823,City Hall - Washington St & 1 St,HB105,Stevens - River Ter & 6 St,HB602,40.737360,-74.030970,40.743133,-74.026989,member

### JSON Files

In [74]:
json_file = (
    spark.read.format("json")
    .option("inferSchema", True)
    .option("header", True)
    .option("multiLine", False)
    .load("/Users/pius/Projects/analytics-engineering/Spark/data/drivers.json")
)

In [75]:
json_file.limit(10).toPandas()

,code,dob,driverId,driverRef,name,nationality,number,url
0,HAM,1985-01-07,1,hamilton,"(Lewis, Hamilton)",British,44,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,HEI,1977-05-10,2,heidfeld,"(Nick, Heidfeld)",German,\N,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,ROS,1985-06-27,3,rosberg,"(Nico, Rosberg)",German,6,http://en.wikipedia.org/wiki/Nico_Rosberg
3,ALO,1981-07-29,4,alonso,"(Fernando, Alonso)",Spanish,14,http://en.wikipedia.org/wiki/Fernando_Alonso
4,KOV,1981-10-19,5,kovalainen,"(Heikki, Kovalainen)",Finnish,\N,http://en.wikipedia.org/wiki/Heikki_Kovalainen
5,NAK,1985-01-11,6,nakajima,"(Kazuki, Nakajima)",Japanese,\N,http://en.wikipedia.org/wiki/Kazuki_Nakajima
6,BOU,1979-02-28,7,bourdais,"(Sébastien, Bourdais)",French,\N,http://en.wikipedia.org/wiki/S%C3%A9bastien_Bo...
7,RAI,1979-10-17,8,raikkonen,"(Kimi, Räikkönen)",Finnish,7,http://en.wikipedia.org/wiki/Kimi_R%C3%A4ikk%C...
8,KUB,1984-12-07,9,kubica,"(Robert, Kubica)",Polish,88,http://en.wikipedia.org/wiki/Robert_Kubica
9,GLO,1982-03-18,10,glock,"(Timo, Glock)",German,\N,http://en.wikipedia.org/wiki/Timo_Glock

### Schema Definition

In [76]:
trips.printSchema()

root
 |-- ride_id: string (nullable = true)
 |-- rideable_type: string (nullable = true)
 |-- started_at: timestamp (nullable = true)
 |-- ended_at: timestamp (nullable = true)
 |-- start_station_name: string (nullable = true)
 |-- start_station_id: string (nullable = true)
 |-- end_station_name: string (nullable = true)
 |-- end_station_id: string (nullable = true)
 |-- start_lat: double (nullable = true)
 |-- start_lng: double (nullable = true)
 |-- end_lat: double (nullable = true)
 |-- end_lng: double (nullable = true)
 |-- member_casual: string (nullable = true)

In [77]:
trips.printSchema()

root
 |-- ride_id: string (nullable = true)
 |-- rideable_type: string (nullable = true)
 |-- started_at: timestamp (nullable = true)
 |-- ended_at: timestamp (nullable = true)
 |-- start_station_name: string (nullable = true)
 |-- start_station_id: string (nullable = true)
 |-- end_station_name: string (nullable = true)
 |-- end_station_id: string (nullable = true)
 |-- start_lat: double (nullable = true)
 |-- start_lng: double (nullable = true)
 |-- end_lat: double (nullable = true)
 |-- end_lng: double (nullable = true)
 |-- member_casual: string (nullable = true)

#### StructType() - Programmatic way to define schema

In [78]:
from pyspark.sql.types import *
from pyspark.sql.functions import *

### Data Transformation with PySpark

In [79]:
trips.select("ride_id", "rideable_type").show()

+----------------+-------------+
|         ride_id|rideable_type|
+----------------+-------------+
|172DBBFC733F03CE|electric_bike|
|D20BBA4860FE736C|electric_bike|
|86F89348995D0E6E| classic_bike|
|AA55A717B7EC1D10| classic_bike|
|C72953D91E986DA7| classic_bike|
|23A1827EA03A9AC2|electric_bike|
|6C0E882AE20AC640|electric_bike|
|FC4AEE485D39016D|electric_bike|
|3E4D96936A8660C6|electric_bike|
|9F2FBA8132468A3B|electric_bike|
|B71B07C28733404F|electric_bike|
|2EE1AB7AFEFB4CBB| classic_bike|
|A7493DA7AFDDBC44| classic_bike|
|7A956542D29EA30E| classic_bike|
|157EFB12EA94DA9A|electric_bike|
|3A54C7F77E03FB73| classic_bike|
|94374385A5951BEE| classic_bike|
|5E9040B2EF62AE11|electric_bike|
|99D204D580A9BD0C|electric_bike|
|7C3E2DA95C52FDFB|electric_bike|
+----------------+-------------+
only showing top 20 rows

In [80]:
trips.select(col("ride_id"), col("rideable_type")).show()

+----------------+-------------+
|         ride_id|rideable_type|
+----------------+-------------+
|172DBBFC733F03CE|electric_bike|
|D20BBA4860FE736C|electric_bike|
|86F89348995D0E6E| classic_bike|
|AA55A717B7EC1D10| classic_bike|
|C72953D91E986DA7| classic_bike|
|23A1827EA03A9AC2|electric_bike|
|6C0E882AE20AC640|electric_bike|
|FC4AEE485D39016D|electric_bike|
|3E4D96936A8660C6|electric_bike|
|9F2FBA8132468A3B|electric_bike|
|B71B07C28733404F|electric_bike|
|2EE1AB7AFEFB4CBB| classic_bike|
|A7493DA7AFDDBC44| classic_bike|
|7A956542D29EA30E| classic_bike|
|157EFB12EA94DA9A|electric_bike|
|3A54C7F77E03FB73| classic_bike|
|94374385A5951BEE| classic_bike|
|5E9040B2EF62AE11|electric_bike|
|99D204D580A9BD0C|electric_bike|
|7C3E2DA95C52FDFB|electric_bike|
+----------------+-------------+
only showing top 20 rows

#### Using ALIAS

In [81]:
trips.select(col("ride_id").alias("rideId")).show()

+----------------+
|          rideId|
+----------------+
|172DBBFC733F03CE|
|D20BBA4860FE736C|
|86F89348995D0E6E|
|AA55A717B7EC1D10|
|C72953D91E986DA7|
|23A1827EA03A9AC2|
|6C0E882AE20AC640|
|FC4AEE485D39016D|
|3E4D96936A8660C6|
|9F2FBA8132468A3B|
|B71B07C28733404F|
|2EE1AB7AFEFB4CBB|
|A7493DA7AFDDBC44|
|7A956542D29EA30E|
|157EFB12EA94DA9A|
|3A54C7F77E03FB73|
|94374385A5951BEE|
|5E9040B2EF62AE11|
|99D204D580A9BD0C|
|7C3E2DA95C52FDFB|
+----------------+
only showing top 20 rows

### Filtering Data

#### Scenario 1

In [82]:
trips.filter(col("member_casual") == "casual").show()

+----------------+-------------+--------------------+--------------------+--------------------+----------------+--------------------+--------------+------------------+------------------+-----------------+------------------+-------------+
|         ride_id|rideable_type|          started_at|            ended_at|  start_station_name|start_station_id|    end_station_name|end_station_id|         start_lat|         start_lng|          end_lat|           end_lng|member_casual|
+----------------+-------------+--------------------+--------------------+--------------------+----------------+--------------------+--------------+------------------+------------------+-----------------+------------------+-------------+
|D20BBA4860FE736C|electric_bike|2024-10-03 19:20:...|2024-10-03 19:31:...|         Oakland Ave|           JC022|Stevens - River T...|         HB602|        40.7376037|       -74.0524783|40.74313282710551|-74.02698867022991|       casual|
|86F89348995D0E6E| classic_bike|2024-10-20 12:14:...|2024-10-20 12:28:...|         Oakland Ave|           JC022|South Waterfront ...|         HB103|        40.7376037|       -74.0524783|40.73698221818716|-74.02778059244156|       casual|
|C2C88331149C15EC| classic_bike|2024-10-02 16:49:...|2024-10-02 17:02:...|      Pershing Field|           JC024|South Waterfront ...|         HB103|      40.742677141|     -74.051788633|40.73698221818716|-74.02778059244156|       casual|
|3D9E3CCA2E6622DC| classic_bike|2024-10-14 11:35:...|2024-10-14 12:41:...|      Pershing Field|           JC024|South Waterfront ...|         HB103|      40.742677141|     -74.051788633|40.73698221818716|-74.02778059244156|       casual|
|A10ADE83E52961FF|electric_bike|2024-10-05 14:05:...|2024-10-05 14:12:...|City Hall - Washi...|           HB105|Hoboken Ave at Mo...|         JC105|          40.73736|         -74.03097|40.73520838045357|-74.04696375131607|       casual|
|62B7DD21F6866DAC|electric_bike|2024-10-18 23:16:...|2024-10-18 23:27:...|        Manila & 1st|           JC082|Hoboken Ave at Mo...|         JC105|40.721650724879986|-74.04288411140442|40.73520838045357|-74.04696375131607|       casual|
|A72CDF271E53BE2D| classic_bike|2024-10-17 17:23:...|2024-10-17 17:32:...|        Manila & 1st|           JC082|Hoboken Ave at Mo...|         JC105|40.721650724879986|-74.04288411140442|40.73520838045357|-74.04696375131607|       casual|
|D7A58CAA45D856B9|electric_bike|2024-10-20 02:34:...|2024-10-20 02:41:...|City Hall - Washi...|           HB105|Hoboken Ave at Mo...|         JC105|          40.73736|         -74.03097|40.73520838045357|-74.04696375131607|       casual|
|F4A543BABEEDAADC|electric_bike|2024-10-19 23:57:...|2024-10-20 00:03:...|City Hall - Washi...|           HB105|Hoboken Ave at Mo...|         JC105|          40.73736|         -74.03097|40.73520838045357|-74.04696375131607|       casual|
|1131F4B0AFD3D203|electric_bike|2024-10-18 11:57:...|2024-10-18 12:15:...|City Hall - Washi...|           HB105|      Journal Square|         JC103|          40.73736|         -74.03097|         40.73367|          -74.0625|       casual|
|502B042CB54AA019|electric_bike|2024-10-10 16:24:...|2024-10-10 16:51:...|         Exchange Pl|           JC116|      Van Vorst Park|         JC035| 40.71636596185077|  -74.034343957901|      40.71848892|     -74.047726625|       casual|
|6005898A9B3D0E83|electric_bike|2024-10-18 15:30:...|2024-10-18 15:36:...|        Manila & 1st|           JC082|      Van Vorst Park|         JC035|40.721650724879986|-74.04288411140442|      40.71848892|     -74.047726625|       casual|
|3C3860EBEAE76BE0|electric_bike|2024-10-12 12:31:...|2024-10-12 12:42:...|         Oakland Ave|           JC022|      Van Vorst Park|         JC035|        40.7376037|       -74.0524783|      40.71848892|     -74.047726625|       casual|
|2431CF29C1FAE369| classic_bike|2024-10-29 12:42:...|2024-10-29 12:52:...|         Oakland Ave|           JC022|      Van Vorst Park|         JC035|        40.7376037|       -74.0524783|      40.71848892|     -74.047726625|       casual|
|FF7CB1A68CC437E9| classic_bike|2024-10-06 15:49:...|2024-10-06 15:58:...|       Washington St|           JC098|      Columbus Drive|         JC014|        40.7242941|       -74.0354826|40.71835519823214|-74.03891444206238|       casual|
|3C8E1EA4C7920AED| classic_bike|2024-10-06 15:45:...|2024-10-06 15:58:...|       Washington St|           JC098|      Columbus Drive|         JC014|        40.7242941|       -74.0354826|40.71835519823214|-74.03891444206238|       casual|
|B23A8AA54E7203B8| classic_bike|2024-10-02 16:31:...|2024-10-02 16:45:...|       Washington St|           JC098|South Waterfront ...|         HB103|        40.7242941|       -74.0354826|40.73698221818716|-74.02778059244156|       casual|
|29528F6199ED5592|electric_bike|2024-10-09 15:03:...|2024-10-09 15:13:...|         Exchange Pl|           JC116|Baldwin at Montgo...|         JC020| 40.71636596185077|  -74.034343957901|       40.7236589|       -74.0641943|       casual|
|6BBC64E3B61FADDA|electric_bike|2024-10-19 18:46:...|2024-10-19 18:52:...|         Oakland Ave|           JC022|Hoboken Ave at Mo...|         JC105|        40.7376037|       -74.0524783|40.73520838045357|-74.04696375131607|       casual|
|64FCFD32B0B8F104|electric_bike|2024-10-22 18:42:...|2024-10-22 18:55:...|      Riverview Park|           JC057|     Brunswick & 6th|         JC081|        40.7443187|       -74.0439909|40.72601172964625|-74.05038893222809|       casual|
+----------------+-------------+--------------------+--------------------+--------------------+----------------+--------------------+--------------+------------------+------------------+-----------------+------------------+-------------+
only showing top 20 rows

#### Scenario 2

In [83]:
trips.filter(
    (col("member_casual") == "casual") & (col("rideable_type") == "docked_bike")
).show()

+----------------+-------------+-------------------+-------------------+--------------------+----------------+--------------------+--------------+---------+----------+---------+----------+-------------+
|         ride_id|rideable_type|         started_at|           ended_at|  start_station_name|start_station_id|    end_station_name|end_station_id|start_lat| start_lng|  end_lat|   end_lng|member_casual|
+----------------+-------------+-------------------+-------------------+--------------------+----------------+--------------------+--------------+---------+----------+---------+----------+-------------+
|5E8C8B7DFFA9C73E|  docked_bike|2022-08-20 01:17:27|2022-08-20 02:01:02|South Waterfront ...|           HB103|Hoboken Terminal ...|         HB101|40.736982|-74.027781|40.735938|-74.030305|       casual|
|0A0EFF1E90C8710F|  docked_bike|2022-08-06 20:06:16|2022-08-06 20:18:10|South Waterfront ...|           HB103|Mama Johnson Fiel...|         HB404|40.736982|-74.027781| 40.74314|-74.040041|       casual|
|2D11D25A580CD96D|  docked_bike|2022-08-25 19:23:45|2022-08-25 19:33:16|South Waterfront ...|           HB103|  Willow Ave & 12 St|         HB505|40.736982|-74.027781|40.751867|-74.030377|       casual|
|3C306F01DE0D5094|  docked_bike|2022-08-28 02:36:45|2022-08-28 03:03:13|South Waterfront ...|           HB103|11 St & Washingto...|         HB502|40.736982|-74.027781|40.749985| -74.02715|       casual|
|43CAE3DFBB65FF39|  docked_bike|2022-08-28 02:37:04|2022-08-28 03:03:23|South Waterfront ...|           HB103|11 St & Washingto...|         HB502|40.736982|-74.027781|40.749985| -74.02715|       casual|
|B2992F7EF2BAE28E|  docked_bike|2022-08-16 09:53:30|2022-08-16 10:04:53|Mama Johnson Fiel...|           HB404|Clinton St & Newa...|         HB409| 40.74314|-74.040041| 40.73743| -74.03571|       casual|
|378EA546356D8F18|  docked_bike|2022-08-25 08:47:42|2022-09-02 15:22:47|Mama Johnson Fiel...|           HB404|Clinton St & Newa...|         HB409| 40.74314|-74.040041| 40.73743| -74.03571|       casual|
|864BA4658C903AFB|  docked_bike|2022-08-27 00:37:19|2022-08-27 01:54:05|South Waterfront ...|           HB103|9 St HBLR - Jacks...|         HB305|40.736982|-74.027781|40.747907|-74.038412|       casual|
|D9DE298BC9A75E9B|  docked_bike|2022-08-28 10:15:17|2022-08-28 10:58:44|South Waterfront ...|           HB103|12 St & Sinatra Dr N|         HB201|40.736982|-74.027781|40.750604| -74.02402|       casual|
|B61AB37DE31E4DCE|  docked_bike|2022-08-28 10:17:38|2022-08-28 10:59:45|South Waterfront ...|           HB103|12 St & Sinatra Dr N|         HB201|40.736982|-74.027781|40.750604| -74.02402|       casual|
|2D769593FFD81415|  docked_bike|2022-08-28 01:04:24|2022-08-28 01:36:22|South Waterfront ...|           HB103|12 St & Sinatra Dr N|         HB201|40.736982|-74.027781|40.750604| -74.02402|       casual|
|CD5E9C84A41A1679|  docked_bike|2022-08-13 19:27:01|2022-08-13 19:58:11|South Waterfront ...|           HB103|12 St & Sinatra Dr N|         HB201|40.736982|-74.027781|40.750604| -74.02402|       casual|
|730AA65A5FCB1645|  docked_bike|2022-08-28 01:06:00|2022-08-28 01:36:06|South Waterfront ...|           HB103|12 St & Sinatra Dr N|         HB201|40.736982|-74.027781|40.750604| -74.02402|       casual|
|7DFA071267876375|  docked_bike|2022-08-14 02:30:39|2022-08-14 02:37:54|South Waterfront ...|           HB103|12 St & Sinatra Dr N|         HB201|40.736982|-74.027781|40.750604| -74.02402|       casual|
|FA53FA63A2921768|  docked_bike|2022-08-08 19:46:31|2022-08-08 19:59:21|       Fairmount Ave|           JC093|           City Hall|         JC003|40.725726|-74.071959|40.717733|-74.043845|       casual|
|13AAAC577C32A4F3|  docked_bike|2022-08-06 22:15:28|2022-08-06 22:30:37|South Waterfront ...|           HB103|     4 St & Grand St|         HB301|40.736982|-74.027781|40.742258|-74.035111|       casual|
|138C568F955E8FCA|  docked_bike|2022-08-06 22:15:34|2022-08-06 22:30:43|South Waterfront ...|           HB103|     4 St & Grand St|         HB301|40.736982|-74.027781|40.742258|-74.035111|       casual|
|53D3A01B6A4558C1|  docked_bike|2022-08-06 22:15:35|2022-08-06 22:31:05|South Waterfront ...|           HB103|     4 St & Grand St|         HB301|40.736982|-74.027781|40.742258|-74.035111|       casual|
|BD5CCA32B552AE3D|  docked_bike|2022-08-28 17:47:40|2022-08-28 20:02:50|            Union St|           JC051|            Union St|         JC051|40.718211|-74.083639|40.718211|-74.083639|       casual|
|226B441B67D145D0|  docked_bike|2022-08-21 12:49:40|2022-08-21 14:48:46|            Union St|           JC051|            Union St|         JC051|40.718211|-74.083639|40.718211|-74.083639|       casual|
+----------------+-------------+-------------------+-------------------+--------------------+----------------+--------------------+--------------+---------+----------+---------+----------+-------------+
only showing top 20 rows

#### Scenario 3

In [84]:
trips.filter((col("ride_id").isNull())).show()

+-------+-------------+----------+--------+------------------+----------------+----------------+--------------+---------+---------+-------+-------+-------------+
|ride_id|rideable_type|started_at|ended_at|start_station_name|start_station_id|end_station_name|end_station_id|start_lat|start_lng|end_lat|end_lng|member_casual|
+-------+-------------+----------+--------+------------------+----------------+----------------+--------------+---------+---------+-------+-------+-------------+
+-------+-------------+----------+--------+------------------+----------------+----------------+--------------+---------+---------+-------+-------+-------------+

In [85]:
trips.filter((col("start_station_id").isNull()) & (col("ride_id").isNull())).show()

+-------+-------------+----------+--------+------------------+----------------+----------------+--------------+---------+---------+-------+-------+-------------+
|ride_id|rideable_type|started_at|ended_at|start_station_name|start_station_id|end_station_name|end_station_id|start_lat|start_lng|end_lat|end_lng|member_casual|
+-------+-------------+----------+--------+------------------+----------------+----------------+--------------+---------+---------+-------+-------+-------------+
+-------+-------------+----------+--------+------------------+----------------+----------------+--------------+---------+---------+-------+-------+-------------+

In [86]:
trips.where((col("start_station_name") == "Warren St")).show()

+----------------+-------------+--------------------+--------------------+------------------+----------------+--------------------+--------------+----------+------------+-----------------+------------------+-------------+
|         ride_id|rideable_type|          started_at|            ended_at|start_station_name|start_station_id|    end_station_name|end_station_id| start_lat|   start_lng|          end_lat|           end_lng|member_casual|
+----------------+-------------+--------------------+--------------------+------------------+----------------+--------------------+--------------+----------+------------+-----------------+------------------+-------------+
|143732490A22F95A| classic_bike|2024-10-26 09:54:...|2024-10-26 10:12:...|         Warren St|           JC006|Stevens - River T...|         HB602|40.7211236|-74.03805095|40.74313282710551|-74.02698867022991|       member|
|23BDC5B0B86C99B4| classic_bike|2024-10-26 10:08:...|2024-10-26 10:49:...|         Warren St|           JC006|Stevens - River T...|         HB602|40.7211236|-74.03805095|40.74313282710551|-74.02698867022991|       member|
|C4A503269F67DEF5|electric_bike|2024-10-08 06:52:...|2024-10-08 07:03:...|         Warren St|           JC006|Stevens - River T...|         HB602|40.7211236|-74.03805095|40.74313282710551|-74.02698867022991|       member|
|020BBEBBBA073A56|electric_bike|2024-10-10 18:07:...|2024-10-10 18:26:...|         Warren St|           JC006|  Madison St & 10 St|         HB503|40.7211236|-74.03805095|40.74994325412246|-74.03586477041245|       casual|
|864AA2FFA054D249| classic_bike|2024-10-18 14:45:...|2024-10-18 14:56:...|         Warren St|           JC006|Hoboken Terminal ...|         HB102|40.7211236|-74.03805095| 40.7360676564825|-74.02912706136703|       casual|
|1EC14C7D1D6CF495| classic_bike|2024-10-01 14:22:...|2024-10-01 14:42:...|         Warren St|           JC006|    Grand St & 14 St|         HB506|40.7211236|-74.03805095|         40.75409|          -74.0316|       member|
|5D90D748C2CD4FC1| classic_bike|2024-10-03 11:28:...|2024-10-03 11:45:...|         Warren St|           JC006|    Grand St & 14 St|         HB506|40.7211236|-74.03805095|         40.75409|          -74.0316|       member|
|8FF8B04EA837BD09| classic_bike|2024-10-30 20:43:...|2024-10-30 20:52:...|         Warren St|           JC006|Hoboken Terminal ...|         HB102|40.7211236|-74.03805095| 40.7360676564825|-74.02912706136703|       member|
|8AC387A0A52B3F16|electric_bike|2024-10-22 17:06:...|2024-10-22 17:14:...|         Warren St|           JC006|Hoboken Ave at Mo...|         JC105|40.7211236|-74.03805095|40.73520838045357|-74.04696375131607|       member|
|D71F5894E15E9F50| classic_bike|2024-10-05 09:03:...|2024-10-05 09:36:...|         Warren St|           JC006|        Glenwood Ave|         JC094|40.7211236|-74.03805095|40.72755146730012|-74.07106071710587|       member|
|48F625871EE4F933| classic_bike|2024-10-23 10:50:...|2024-10-23 11:36:...|         Warren St|           JC006|      Van Vorst Park|         JC035|40.7211236|-74.03805095|      40.71848892|     -74.047726625|       member|
|2FBF00A2AF7298B8| classic_bike|2024-10-13 14:16:...|2024-10-13 14:24:...|         Warren St|           JC006|      Van Vorst Park|         JC035|40.7211236|-74.03805095|      40.71848892|     -74.047726625|       member|
|A6323C7B12B2AB9E| classic_bike|2024-10-26 13:09:...|2024-10-26 13:16:...|         Warren St|           JC006|      Van Vorst Park|         JC035|40.7211236|-74.03805095|      40.71848892|     -74.047726625|       member|
|988BE9712CFFB2E8|electric_bike|2024-10-22 19:31:...|2024-10-22 19:36:...|         Warren St|           JC006|      Van Vorst Park|         JC035|40.7211236|-74.03805095|      40.71848892|     -74.047726625|       member|
|47C960D5063D24AC|electric_bike|2024-10-15 20:44:...|2024-10-15 20:50:...|         Warren St|           JC006|      Van Vorst Park|         JC035|40.7211236|-74.03805095|      40.71848892|     -74.047726625|       member|
|C8DBF03E8F6DC05C|electric_bike|2024-10-06 16:12:...|2024-10-06 16:17:...|         Warren St|           JC006|        Morris Canal|         JC072|40.7211236|-74.03805095| 40.7124188237569|-74.03852552175522|       member|
|A9EDC38C8EA5981F| classic_bike|2024-10-19 13:08:...|2024-10-19 13:21:...|         Warren St|           JC006|Church Sq Park - ...|         HB601|40.7211236|-74.03805095|40.74265933273143|-74.03223305940628|       member|
|46F1729ACA247F5B| classic_bike|2024-10-05 20:55:...|2024-10-05 20:59:...|         Warren St|           JC006|        Morris Canal|         JC072|40.7211236|-74.03805095| 40.7124188237569|-74.03852552175522|       member|
|0A3734095D0B8821| classic_bike|2024-10-24 19:28:...|2024-10-24 19:39:...|         Warren St|           JC006|   JC Medical Center|         JC110|40.7211236|-74.03805095|   40.71539114317|-74.04969155788422|       member|
|CD700162B6400BD1|electric_bike|2024-10-13 10:13:...|2024-10-13 10:17:...|         Warren St|           JC006|        Morris Canal|         JC072|40.7211236|-74.03805095| 40.7124188237569|-74.03852552175522|       casual|
+----------------+-------------+--------------------+--------------------+------------------+----------------+--------------------+--------------+----------+------------+-----------------+------------------+-------------+
only showing top 20 rows

### Handling Null Values

PySpark provides several functions to handle null values in DataFrames, including `fillna()`, `dropna()`, and `replace()`. These functions allow you to fill, drop, or replace null values in your data as needed.

#### dropna()

When using .`dropna()`, you can specify the `how` parameter to determine how rows with null values should be dropped. The options for the `how` parameter are:

- `any`: Drops a row if it contains any null values (default behavior).
- `all`: Drops a row only if all values in that row are null.

In [87]:
trips = trips.dropna(subset=["ride_id", "start_lat", "end_lat", "start_lng", "end_lng"])

In [88]:
trips.count()

4689909

#### withColumnRenamed()

In [89]:
trips.withColumnRenamed("ride_id", "rideId").show()

+----------------+-------------+--------------------+--------------------+--------------------+----------------+--------------------+--------------+-----------------+------------------+-----------------+------------------+-------------+
|          rideId|rideable_type|          started_at|            ended_at|  start_station_name|start_station_id|    end_station_name|end_station_id|        start_lat|         start_lng|          end_lat|           end_lng|member_casual|
+----------------+-------------+--------------------+--------------------+--------------------+----------------+--------------------+--------------+-----------------+------------------+-----------------+------------------+-------------+
|172DBBFC733F03CE|electric_bike|2024-10-10 14:54:...|2024-10-10 15:04:...|         Oakland Ave|           JC022|Stevens - River T...|         HB602|       40.7376037|       -74.0524783|40.74313282710551|-74.02698867022991|       member|
|D20BBA4860FE736C|electric_bike|2024-10-03 19:20:...|2024-10-03 19:31:...|         Oakland Ave|           JC022|Stevens - River T...|         HB602|       40.7376037|       -74.0524783|40.74313282710551|-74.02698867022991|       casual|
|86F89348995D0E6E| classic_bike|2024-10-20 12:14:...|2024-10-20 12:28:...|         Oakland Ave|           JC022|South Waterfront ...|         HB103|       40.7376037|       -74.0524783|40.73698221818716|-74.02778059244156|       casual|
|AA55A717B7EC1D10| classic_bike|2024-10-20 14:40:...|2024-10-20 14:55:...|         Oakland Ave|           JC022|      Columbus Drive|         JC014|       40.7376037|       -74.0524783|40.71835519823214|-74.03891444206238|       member|
|C72953D91E986DA7| classic_bike|2024-10-20 08:37:...|2024-10-20 08:42:...|     Brunswick & 6th|           JC081|       Washington St|         JC098|40.72601172964625|-74.05038893222809|       40.7242941|       -74.0354826|       member|
|23A1827EA03A9AC2|electric_bike|2024-10-28 19:20:...|2024-10-28 19:25:...|         Oakland Ave|           JC022|Hoboken Ave at Mo...|         JC105|       40.7376037|       -74.0524783|40.73520838045357|-74.04696375131607|       member|
|6C0E882AE20AC640|electric_bike|2024-10-08 10:41:...|2024-10-08 10:44:...|      Pershing Field|           JC024| Leonard Gordon Park|         JC080|     40.742677141|     -74.051788633|40.74590996631558| -74.0572714805603|       member|
|FC4AEE485D39016D|electric_bike|2024-10-25 21:02:...|2024-10-25 21:11:...|      Pershing Field|           JC024| Leonard Gordon Park|         JC080|     40.742677141|     -74.051788633|40.74590996631558| -74.0572714805603|       member|
|3E4D96936A8660C6|electric_bike|2024-10-08 12:17:...|2024-10-08 12:20:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|
|9F2FBA8132468A3B|electric_bike|2024-10-28 11:00:...|2024-10-28 11:03:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|
|B71B07C28733404F|electric_bike|2024-10-26 11:39:...|2024-10-26 11:45:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|
|2EE1AB7AFEFB4CBB| classic_bike|2024-10-02 23:43:...|2024-10-02 23:47:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|
|A7493DA7AFDDBC44| classic_bike|2024-10-12 12:48:...|2024-10-12 13:16:...|         Exchange Pl|           JC116|Stevens - River T...|         HB602|40.71636596185077|  -74.034343957901|40.74313282710551|-74.02698867022991|       member|
|7A956542D29EA30E| classic_bike|2024-10-24 17:48:...|2024-10-24 17:53:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|
|157EFB12EA94DA9A|electric_bike|2024-10-02 14:37:...|2024-10-02 14:41:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|
|3A54C7F77E03FB73| classic_bike|2024-10-06 01:42:...|2024-10-06 01:48:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|
|94374385A5951BEE| classic_bike|2024-10-22 16:38:...|2024-10-22 16:45:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|
|5E9040B2EF62AE11|electric_bike|2024-10-21 13:45:...|2024-10-21 13:57:...|      Pershing Field|           JC024|Stevens - River T...|         HB602|     40.742677141|     -74.051788633|40.74313282710551|-74.02698867022991|       member|
|99D204D580A9BD0C|electric_bike|2024-10-07 13:39:...|2024-10-07 13:48:...|      Pershing Field|           JC024|Stevens - River T...|         HB602|     40.742677141|     -74.051788633|40.74313282710551|-74.02698867022991|       member|
|7C3E2DA95C52FDFB|electric_bike|2024-10-03 08:52:...|2024-10-03 09:02:...|      Pershing Field|           JC024|Stevens - River T...|         HB602|     40.742677141|     -74.051788633|40.74313282710551|-74.02698867022991|       member|
+----------------+-------------+--------------------+--------------------+--------------------+----------------+--------------------+--------------+-----------------+------------------+-----------------+------------------+-------------+
only showing top 20 rows

#### withColumn() - Adding a new column to the DataFrame

In [90]:
trips = trips.withColumn(
    "rideDurationMinutes",
    round((col("ended_at").cast("long") - col("started_at").cast("long")) / 60, 2),
)

trips = trips.withColumn(
    "rideDurationMinutes",
    when(col("rideDurationMinutes") < 0, col("rideDurationMinutes") + 60).otherwise(
        col("rideDurationMinutes")
    ),
)

trips = trips.withColumn("rideDurationHours", round(col("rideDurationMinutes") / 60, 2))

In [91]:
trips.show()

+----------------+-------------+--------------------+--------------------+--------------------+----------------+--------------------+--------------+-----------------+------------------+-----------------+------------------+-------------+-------------------+-----------------+
|         ride_id|rideable_type|          started_at|            ended_at|  start_station_name|start_station_id|    end_station_name|end_station_id|        start_lat|         start_lng|          end_lat|           end_lng|member_casual|rideDurationMinutes|rideDurationHours|
+----------------+-------------+--------------------+--------------------+--------------------+----------------+--------------------+--------------+-----------------+------------------+-----------------+------------------+-------------+-------------------+-----------------+
|172DBBFC733F03CE|electric_bike|2024-10-10 14:54:...|2024-10-10 15:04:...|         Oakland Ave|           JC022|Stevens - River T...|         HB602|       40.7376037|       -74.0524783|40.74313282710551|-74.02698867022991|       member|               9.72|             0.16|
|D20BBA4860FE736C|electric_bike|2024-10-03 19:20:...|2024-10-03 19:31:...|         Oakland Ave|           JC022|Stevens - River T...|         HB602|       40.7376037|       -74.0524783|40.74313282710551|-74.02698867022991|       casual|              11.42|             0.19|
|86F89348995D0E6E| classic_bike|2024-10-20 12:14:...|2024-10-20 12:28:...|         Oakland Ave|           JC022|South Waterfront ...|         HB103|       40.7376037|       -74.0524783|40.73698221818716|-74.02778059244156|       casual|               13.6|             0.23|
|AA55A717B7EC1D10| classic_bike|2024-10-20 14:40:...|2024-10-20 14:55:...|         Oakland Ave|           JC022|      Columbus Drive|         JC014|       40.7376037|       -74.0524783|40.71835519823214|-74.03891444206238|       member|               15.4|             0.26|
|C72953D91E986DA7| classic_bike|2024-10-20 08:37:...|2024-10-20 08:42:...|     Brunswick & 6th|           JC081|       Washington St|         JC098|40.72601172964625|-74.05038893222809|       40.7242941|       -74.0354826|       member|               5.35|             0.09|
|23A1827EA03A9AC2|electric_bike|2024-10-28 19:20:...|2024-10-28 19:25:...|         Oakland Ave|           JC022|Hoboken Ave at Mo...|         JC105|       40.7376037|       -74.0524783|40.73520838045357|-74.04696375131607|       member|                5.0|             0.08|
|6C0E882AE20AC640|electric_bike|2024-10-08 10:41:...|2024-10-08 10:44:...|      Pershing Field|           JC024| Leonard Gordon Park|         JC080|     40.742677141|     -74.051788633|40.74590996631558| -74.0572714805603|       member|               2.77|             0.05|
|FC4AEE485D39016D|electric_bike|2024-10-25 21:02:...|2024-10-25 21:11:...|      Pershing Field|           JC024| Leonard Gordon Park|         JC080|     40.742677141|     -74.051788633|40.74590996631558| -74.0572714805603|       member|               8.33|             0.14|
|3E4D96936A8660C6|electric_bike|2024-10-08 12:17:...|2024-10-08 12:20:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|                3.4|             0.06|
|9F2FBA8132468A3B|electric_bike|2024-10-28 11:00:...|2024-10-28 11:03:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|               2.53|             0.04|
|B71B07C28733404F|electric_bike|2024-10-26 11:39:...|2024-10-26 11:45:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|               6.08|              0.1|
|2EE1AB7AFEFB4CBB| classic_bike|2024-10-02 23:43:...|2024-10-02 23:47:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|               3.72|             0.06|
|A7493DA7AFDDBC44| classic_bike|2024-10-12 12:48:...|2024-10-12 13:16:...|         Exchange Pl|           JC116|Stevens - River T...|         HB602|40.71636596185077|  -74.034343957901|40.74313282710551|-74.02698867022991|       member|              27.62|             0.46|
|7A956542D29EA30E| classic_bike|2024-10-24 17:48:...|2024-10-24 17:53:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|               5.15|             0.09|
|157EFB12EA94DA9A|electric_bike|2024-10-02 14:37:...|2024-10-02 14:41:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|               3.78|             0.06|
|3A54C7F77E03FB73| classic_bike|2024-10-06 01:42:...|2024-10-06 01:48:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|               5.45|             0.09|
|94374385A5951BEE| classic_bike|2024-10-22 16:38:...|2024-10-22 16:45:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|               6.52|             0.11|
|5E9040B2EF62AE11|electric_bike|2024-10-21 13:45:...|2024-10-21 13:57:...|      Pershing Field|           JC024|Stevens - River T...|         HB602|     40.742677141|     -74.051788633|40.74313282710551|-74.02698867022991|       member|              11.17|             0.19|
|99D204D580A9BD0C|electric_bike|2024-10-07 13:39:...|2024-10-07 13:48:...|      Pershing Field|           JC024|Stevens - River T...|         HB602|     40.742677141|     -74.051788633|40.74313282710551|-74.02698867022991|       member|                9.3|             0.16|
|7C3E2DA95C52FDFB|electric_bike|2024-10-03 08:52:...|2024-10-03 09:02:...|      Pershing Field|           JC024|Stevens - River T...|         HB602|     40.742677141|     -74.051788633|40.74313282710551|-74.02698867022991|       member|               9.95|             0.17|
+----------------+-------------+--------------------+--------------------+--------------------+----------------+--------------------+--------------+-----------------+------------------+-----------------+------------------+-------------+-------------------+-----------------+
only showing top 20 rows

In [92]:
R = 6371.0

lat1 = radians(col("start_lat"))
lat2 = radians(col("end_lat"))
lng1 = radians(col("start_lng"))
lng2 = radians(col("end_lng"))

dlat = lat2 - lat1
dlng = lng2 - lng1

a = pow(sin(dlat / 2.0), 2) + cos(lat1) * cos(lat2) * pow(sin(dlng / 2.0), 2)

c = 2 * asin(sqrt(a))

distance_formula = round(R * c, 2)

trips = trips.withColumn("rideDistanceKM", distance_formula).withColumn(
    "rideDistanceM", distance_formula * 1000
)

In [93]:
trips.printSchema()

root
 |-- ride_id: string (nullable = true)
 |-- rideable_type: string (nullable = true)
 |-- started_at: timestamp (nullable = true)
 |-- ended_at: timestamp (nullable = true)
 |-- start_station_name: string (nullable = true)
 |-- start_station_id: string (nullable = true)
 |-- end_station_name: string (nullable = true)
 |-- end_station_id: string (nullable = true)
 |-- start_lat: double (nullable = true)
 |-- start_lng: double (nullable = true)
 |-- end_lat: double (nullable = true)
 |-- end_lng: double (nullable = true)
 |-- member_casual: string (nullable = true)
 |-- rideDurationMinutes: double (nullable = true)
 |-- rideDurationHours: double (nullable = true)
 |-- rideDistanceKM: double (nullable = true)
 |-- rideDistanceM: double (nullable = true)

In [94]:
trips.filter((col("rideDistanceM") == 0)).show()

+----------------+-------------+--------------------+--------------------+--------------------+----------------+--------------------+--------------+-----------------+------------------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+
|         ride_id|rideable_type|          started_at|            ended_at|  start_station_name|start_station_id|    end_station_name|end_station_id|        start_lat|         start_lng|          end_lat|           end_lng|member_casual|rideDurationMinutes|rideDurationHours|rideDistanceKM|rideDistanceM|
+----------------+-------------+--------------------+--------------------+--------------------+----------------+--------------------+--------------+-----------------+------------------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+
|E12C216DABC5E494| classic_bike|2024-10-31 11:38:...|2024-10-31 11:41:...|       Washington St|           JC098|       Washington St|         JC098|       40.7242941|       -74.0354826|       40.7242941|       -74.0354826|       member|               2.98|             0.05|           0.0|          0.0|
|F9377A40422B8EEE|electric_bike|2024-10-05 14:52:...|2024-10-05 15:11:...|       Washington St|           JC098|       Washington St|         JC098|       40.7242941|       -74.0354826|       40.7242941|       -74.0354826|       member|               18.5|             0.31|           0.0|          0.0|
|07CFD534A7B34060| classic_bike|2024-10-20 21:14:...|2024-10-20 21:16:...|       Washington St|           JC098|       Washington St|         JC098|       40.7242941|       -74.0354826|       40.7242941|       -74.0354826|       member|               2.57|             0.04|           0.0|          0.0|
|56DDC95FF4453BA2|electric_bike|2024-10-05 12:01:...|2024-10-05 12:59:...|       Washington St|           JC098|       Washington St|         JC098|       40.7242941|       -74.0354826|       40.7242941|       -74.0354826|       member|               58.5|             0.98|           0.0|          0.0|
|F195AD0BB916CE89|electric_bike|2024-10-05 12:01:...|2024-10-05 12:59:...|       Washington St|           JC098|       Washington St|         JC098|       40.7242941|       -74.0354826|       40.7242941|       -74.0354826|       member|              58.82|             0.98|           0.0|          0.0|
|7690F004BD5B2031| classic_bike|2024-10-06 15:46:...|2024-10-06 15:47:...|       Washington St|           JC098|       Washington St|         JC098|       40.7242941|       -74.0354826|       40.7242941|       -74.0354826|       casual|               1.45|             0.02|           0.0|          0.0|
|D1FB9BC5F5C68724|electric_bike|2024-10-27 19:53:...|2024-10-27 20:15:...|       Washington St|           JC098|       Washington St|         JC098|       40.7242941|       -74.0354826|       40.7242941|       -74.0354826|       casual|              21.77|             0.36|           0.0|          0.0|
|1BBF404BDCE71257| classic_bike|2024-10-23 15:10:...|2024-10-23 15:32:...|       Washington St|           JC098|       Washington St|         JC098|       40.7242941|       -74.0354826|       40.7242941|       -74.0354826|       casual|               22.5|             0.38|           0.0|          0.0|
|8CCB8C9F7F638D69| classic_bike|2024-10-23 15:35:...|2024-10-23 16:05:...|       Washington St|           JC098|       Washington St|         JC098|       40.7242941|       -74.0354826|       40.7242941|       -74.0354826|       casual|              29.28|             0.49|           0.0|          0.0|
|9F2AEFA57C9F788E| classic_bike|2024-10-30 16:06:...|2024-10-30 16:25:...|9 St HBLR - Jacks...|           HB305|9 St HBLR - Jacks...|         HB305|40.74790720968899|-74.03841152787209|40.74790720968899|-74.03841152787209|       member|              18.87|             0.31|           0.0|          0.0|
|E451ABEFF4994283|electric_bike|2024-10-17 12:46:...|2024-10-17 13:00:...|       Washington St|           JC098|       Washington St|         JC098|       40.7242941|       -74.0354826|       40.7242941|       -74.0354826|       member|              14.87|             0.25|           0.0|          0.0|
|AC6934175F9B3D10| classic_bike|2024-10-26 07:58:...|2024-10-26 08:21:...|       Washington St|           JC098|       Washington St|         JC098|       40.7242941|       -74.0354826|       40.7242941|       -74.0354826|       member|              23.22|             0.39|           0.0|          0.0|
|A086900705665D66|electric_bike|2024-10-14 17:05:...|2024-10-14 17:06:...|       Washington St|           JC098|       Washington St|         JC098|       40.7242941|       -74.0354826|       40.7242941|       -74.0354826|       member|               1.75|             0.03|           0.0|          0.0|
|CE1F83A87D4F7397| classic_bike|2024-10-04 11:23:...|2024-10-04 12:20:...|       Washington St|           JC098|       Washington St|         JC098|       40.7242941|       -74.0354826|       40.7242941|       -74.0354826|       casual|              57.35|             0.96|           0.0|          0.0|
|C726730280C39077|electric_bike|2024-10-14 14:37:...|2024-10-14 14:45:...|       Washington St|           JC098|       Washington St|         JC098|       40.7242941|       -74.0354826|       40.7242941|       -74.0354826|       member|               8.35|             0.14|           0.0|          0.0|
|A821409AE887E77C|electric_bike|2024-10-15 10:07:...|2024-10-15 10:14:...|       Washington St|           JC098|       Washington St|         JC098|       40.7242941|       -74.0354826|       40.7242941|       -74.0354826|       member|               6.03|              0.1|           0.0|          0.0|
|19F1868A5807A161|electric_bike|2024-10-03 18:48:...|2024-10-03 19:00:...|       Washington St|           JC098|       Washington St|         JC098|       40.7242941|       -74.0354826|       40.7242941|       -74.0354826|       member|              12.33|             0.21|           0.0|          0.0|
|13198A1EF2DB5F74|electric_bike|2024-10-15 08:13:...|2024-10-15 08:21:...|9 St HBLR - Jacks...|           HB305|9 St HBLR - Jacks...|         HB305|40.74790720968899|-74.03841152787209|40.74790720968899|-74.03841152787209|       member|               8.17|             0.14|           0.0|          0.0|
|5FC536D33DD8D3A9|electric_bike|2024-10-04 08:08:...|2024-10-04 08:19:...|9 St HBLR - Jacks...|           HB305|9 St HBLR - Jacks...|         HB305|40.74790720968899|-74.03841152787209|40.74790720968899|-74.03841152787209|       member|               10.5|             0.18|           0.0|          0.0|
|6D61579A31531C95|electric_bike|2024-10-18 08:07:...|2024-10-18 08:16:...|9 St HBLR - Jacks...|           HB305|9 St HBLR - Jacks...|         HB305|40.74790720968899|-74.03841152787209|40.74790720968899|-74.03841152787209|       member|               9.45|             0.16|           0.0|          0.0|
+----------------+-------------+--------------------+--------------------+--------------------+----------------+--------------------+--------------+-----------------+------------------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+
only showing top 20 rows

In [95]:
trips.filter((col("rideDistanceM") == 0)).count()

261413

#### Type Casting

In [96]:
trips.withColumn("ride_id", col("ride_id").cast(StringType()))

DataFrame[ride_id: string, rideable_type: string, started_at: timestamp, ended_at: timestamp, start_station_name: string, start_station_id: string, end_station_name: string, end_station_id: string, start_lat: double, start_lng: double, end_lat: double, end_lng: double, member_casual: string, rideDurationMinutes: double, rideDurationHours: double, rideDistanceKM: double, rideDistanceM: double]

#### Sort and OrderBy

In [97]:
trips.sort((col("rideDurationMinutes").desc())).show()

+----------------+-------------+-------------------+-------------------+--------------------+----------------+--------------------+--------------+---------+----------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+
|         ride_id|rideable_type|         started_at|           ended_at|  start_station_name|start_station_id|    end_station_name|end_station_id|start_lat| start_lng|          end_lat|           end_lng|member_casual|rideDurationMinutes|rideDurationHours|rideDistanceKM|rideDistanceM|
+----------------+-------------+-------------------+-------------------+--------------------+----------------+--------------------+--------------+---------+----------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+
|AFF1F450B44EF59E|  docked_bike|2021-07-31 19:36:50|2021-12-08 16:38:19|South Waterfront ...|           HB103|Grand Concourse &...|       8303.06|40.736982|-74.027781|        40.846221|        -73.909232|       casual|          187021.48|          3117.02|         15.72|      15720.0|
|C322C213579A803F|  docked_bike|2021-02-06 05:49:33|2021-05-21 15:27:44|     McGinley Square|           JC055|Bloomfield St & 1...|         HB203| 40.72534|-74.067622|         40.75453|         -74.02658|       casual|          150338.18|          2505.64|          4.74|       4740.0|
|6CEB3B83A5FBAF65|electric_bike|2021-06-12 20:37:07|2021-08-06 17:32:56|      Jackson Square|           JC063|Bergen Ave & Steg...|         JC108| 40.71113|  -74.0789|40.70657545063453| -74.0867006778717|       casual|           79015.82|          1316.93|          0.83|        830.0|
|67181F5C39DBDBFF|  docked_bike|2021-06-13 23:49:00|2021-07-31 15:11:57|    7 St & Monroe St|           HB304|W 147 St & Adam C...|       7971.07|40.746412|-74.037977|         40.82281|        -73.937413|       casual|           68602.95|          1143.38|         11.99|      11990.0|
|AF5746957A052C5A|  docked_bike|2021-06-06 12:18:03|2021-07-23 16:53:13|             Hilltop|           JC019|Bergen Ave & Steg...|         JC108|40.731168|-74.057573|40.70657545063453| -74.0867006778717|       casual|           67955.17|          1132.59|          3.67|       3670.0|
|01D7569FCD02C04F|  docked_bike|2021-09-26 12:00:53|2021-11-11 19:58:04|Columbus Park - C...|           HB501|   5 Corners Library|         JC018|40.748161|-74.032453|        40.734961|        -74.059503|       casual|           66717.18|          1111.95|          2.71|       2710.0|
|A066248051114D69|  docked_bike|2021-06-03 19:13:36|2021-07-04 02:09:22|9 St HBLR - Jacks...|           HB305|         Astor Place|         JC077|40.747907|-74.038411|40.71928220070702|-74.07126188278198|       casual|           43615.77|           726.93|          4.22|       4220.0|
|1C0893A074E6C870|  docked_bike|2021-04-24 14:02:52|2021-05-21 00:32:56|Hoboken Ave at Mo...|           JC105|Bloomfield St & 1...|         HB203|40.735208|-74.046964|         40.75453|         -74.02658|       casual|           38070.07|            634.5|          2.75|       2750.0|
|5B210F3FF6C038F3|  docked_bike|2021-06-18 14:06:41|2021-07-12 08:03:58|South Waterfront ...|           HB103|Frederick Douglas...|       7688.12|40.736982| -74.02778|        40.805159|        -73.954692|       casual|           34197.28|           569.95|          9.76|       9760.0|
|FEC2A78FD03ADDF1|  docked_bike|2021-10-25 16:12:28|2021-11-18 08:09:04|        Morris Canal|           JC072|    E 114 St & 1 Ave|       7540.02|40.712419|-74.038526|        40.794566|        -73.936254|       casual|            34076.6|           567.94|         12.56|      12560.0|
|E3C68E77202B45E6|  docked_bike|2021-03-27 14:54:00|2021-04-16 21:22:04|  Liberty Light Rail|           JC052|Westchester Ave &...|       8004.03|40.711242|-74.055701|        40.824956|        -73.891677|       casual|           29188.07|           486.47|         18.73|      18730.0|
|F72BFD1F68EA47AC|  docked_bike|2021-08-26 23:39:00|2021-09-15 20:04:43|12 St & Sinatra Dr N|           HB201|Church Sq Park - ...|         HB601|40.750604| -74.02402|        40.742659|        -74.032233|       casual|           28585.72|           476.43|          1.12|       1120.0|
|83DCB73B50AD617F|  docked_bike|2021-06-06 00:58:36|2021-06-25 21:03:03|       Grove St PATH|           JC005|Washington Pl & 6...|       5838.09|40.719586|-74.043117|      40.73224119|      -74.00026394|       casual|           28564.45|           476.07|          3.88|       3880.0|
|435CB0475E96C883|  docked_bike|2022-05-01 00:30:35|2022-05-20 20:12:05|South Waterfront ...|           HB103|      Lafayette Park|         JC078|40.736982|-74.027781|        40.713464|        -74.062859|       casual|            28541.5|           475.69|          3.95|       3950.0|
|4A116D956E092D28|  docked_bike|2022-07-10 14:05:49|2022-07-27 05:21:52|Hoboken Terminal ...|           HB101|     1 Ave & E 30 St|       6079.03|40.735938|-74.030305|        40.741444|        -73.975361|       casual|           23956.05|           399.27|          4.67|       4670.0|
|8204AAD5D7E50F8A|  docked_bike|2021-06-06 23:18:05|2021-06-22 02:41:16|South Waterfront ...|           HB103|     4 St & Grand St|         HB301|40.736982| -74.02778| 40.7422579775645|-74.03511106967926|       casual|           21803.18|           363.39|          0.85|        850.0|
|BD40D73F4134D242|  docked_bike|2022-07-05 16:09:31|2022-07-18 17:19:15|    Essex Light Rail|           JC038|9 St HBLR - Jacks...|         HB305|40.712774|-74.036486|        40.747907|        -74.038412|       casual|           18789.73|           313.16|          3.91|       3910.0|
|5234D881EC29D815|  docked_bike|2022-06-24 15:39:26|2022-07-07 06:52:57|      Pershing Field|           JC024|        Lincoln Park|         JC053|40.742677|-74.051789|        40.724605|        -74.078406|       casual|           18193.52|           303.23|          3.01|       3010.0|
|14A43A951176806C|  docked_bike|2021-02-03 14:28:31|2021-02-16 04:24:54|     Brunswick & 6th|           JC081|       Grove St PATH|         JC005|40.726012|-74.050389|        40.719586|        -74.043117|       member|           18116.38|           301.94|          0.94|        940.0|
|D5323843A85BFEC3|  docked_bike|2021-06-19 18:49:46|2021-07-01 17:46:29|      Lafayette Park|           JC078|   Madison St & 1 St|         HB402|40.713464|-74.062859|         40.73879|          -74.0393|       casual|           17216.72|           286.95|          3.45|       3450.0|
+----------------+-------------+-------------------+-------------------+--------------------+----------------+--------------------+--------------+---------+----------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+
only showing top 20 rows

In [98]:
trips.sort((col("rideDurationMinutes").asc())).show()

+----------------+-------------+-------------------+-------------------+--------------------+----------------+--------------------+--------------+------------------+------------------+------------------+------------------+-------------+-------------------+-----------------+--------------+-------------+
|         ride_id|rideable_type|         started_at|           ended_at|  start_station_name|start_station_id|    end_station_name|end_station_id|         start_lat|         start_lng|           end_lat|           end_lng|member_casual|rideDurationMinutes|rideDurationHours|rideDistanceKM|rideDistanceM|
+----------------+-------------+-------------------+-------------------+--------------------+----------------+--------------------+--------------+------------------+------------------+------------------+------------------+-------------+-------------------+-----------------+--------------+-------------+
|5471CCE179A9960F| classic_bike|2023-05-03 12:26:39|2023-05-03 12:26:39|             Hilltop|           JC019|             Hilltop|         JC019|        40.7311689|       -74.0575736|        40.7311689|       -74.0575736|       member|                0.0|              0.0|           0.0|          0.0|
|C2ADD557C06E915F| classic_bike|2024-02-07 10:21:19|2024-02-07 10:21:19|        Brunswick St|           JC023|        Brunswick St|         JC023|        40.7241765|       -74.0506564|        40.7241765|       -74.0506564|       member|                0.0|              0.0|           0.0|          0.0|
|0CF2769A91E718C8|  docked_bike|2021-05-19 19:00:38|2021-05-19 19:00:38|        Jersey & 3rd|           JC074|        Jersey & 3rd|         JC074|         40.723331|        -74.045952| 40.72333158646436|-74.04595255851744|       casual|                0.0|              0.0|           0.0|          0.0|
|017103EEA443AB78| classic_bike|2024-02-02 19:17:33|2024-02-02 19:17:33|Hoboken Ave at Mo...|           JC105|Hoboken Ave at Mo...|         JC105| 40.73520838045357|-74.04696375131607| 40.73520838045357|-74.04696375131607|       member|                0.0|              0.0|           0.0|          0.0|
|FF9A083AF6A76137| classic_bike|2023-08-22 18:41:21|2023-08-22 18:41:21|      Pershing Field|           JC024|      Pershing Field|         JC024|      40.742677141|     -74.051788633|      40.742677141|     -74.051788633|       member|                0.0|              0.0|           0.0|          0.0|
|2E07DB7A088F7BC0| classic_bike|2024-02-04 00:18:04|2024-02-04 00:18:04|       Grove St PATH|           JC115|       Grove St PATH|         JC115|          40.71941|         -74.04309|          40.71941|         -74.04309|       member|                0.0|              0.0|           0.0|          0.0|
|5B92C957130BDB18|  docked_bike|2021-05-25 18:24:45|2021-05-25 18:24:45|Columbus Dr at Ex...|           JC106|Columbus Dr at Ex...|         JC106|          40.71687|         -74.03281|          40.71687|         -74.03281|       member|                0.0|              0.0|           0.0|          0.0|
|436FB462F6E040D3| classic_bike|2024-02-10 21:15:25|2024-02-10 21:15:25|Bergen Ave & Sip Ave|           JC109|Bergen Ave & Sip Ave|         JC109| 40.73100888698729|-74.06443700194359| 40.73100888698729|-74.06443700194359|       member|                0.0|              0.0|           0.0|          0.0|
|648E577394A6677C| classic_bike|2022-08-14 16:05:04|2022-08-14 16:05:04|        Brunswick St|           JC023|        Brunswick St|         JC023|        40.7241765|       -74.0506564|        40.7241765|       -74.0506564|       member|                0.0|              0.0|           0.0|          0.0|
|00EFF3D0E5703E6F|electric_bike|2023-02-08 19:53:11|2023-02-08 19:53:11|           City Hall|           JC003|           City Hall|         JC003|        40.7177325|        -74.043845|        40.7177325|        -74.043845|       member|                0.0|              0.0|           0.0|          0.0|
|F33B3707D04608B5|electric_bike|2022-02-10 16:22:13|2022-02-10 16:22:13|  Liberty Light Rail|           JC052|  Liberty Light Rail|         JC052|        40.7112423|       -74.0557013|        40.7112423|       -74.0557013|       casual|                0.0|              0.0|           0.0|          0.0|
|A7AA0AE8BD0C7313|electric_bike|2024-01-14 20:52:44|2024-01-14 20:52:44|   Madison St & 1 St|           HB402|   Madison St & 1 St|         HB402|      40.738782883|     -74.039123178|          40.73879|          -74.0393|       member|                0.0|              0.0|          0.01|         10.0|
|52694E136387FD89| classic_bike|2023-08-19 15:52:36|2023-08-19 15:52:36|Bergen Ave & Sip Ave|           JC109|Bergen Ave & Sip Ave|         JC109|      40.731011033|     -74.064283252| 40.73100888698729|-74.06443700194359|       member|                0.0|              0.0|          0.01|         10.0|
|449BB393CEF79035|electric_bike|2024-01-18 12:55:36|2024-01-18 12:55:36|City Hall - Washi...|           HB105|City Hall - Washi...|         HB105|      40.737185001|     -74.030997634|          40.73736|         -74.03097|       member|                0.0|              0.0|          0.02|         20.0|
|3AE78FF9F47CE756| classic_bike|2022-01-28 08:55:30|2022-01-28 08:55:30|       Grove St PATH|           JC005|       Grove St PATH|         JC005| 40.71958611647166|-74.04311746358871| 40.71958611647166|-74.04311746358871|       member|                0.0|              0.0|           0.0|          0.0|
|BD9AD0EE5DFAF61F| classic_bike|2022-12-02 08:07:29|2022-12-02 08:07:29|Hoboken Terminal ...|           HB101|Hoboken Terminal ...|         HB101|      40.735854745|     -74.030373573| 40.73593758446329|-74.03030455112457|       member|                0.0|              0.0|          0.01|         10.0|
|89B19B53CA34EDEB| classic_bike|2021-07-23 07:13:35|2021-07-23 07:13:35|8 St & Washington St|           HB603|8 St & Washington St|         HB603|40.745983882915624|-74.02819901704788|40.745983882915624|-74.02819901704788|       casual|                0.0|              0.0|           0.0|          0.0|
|455BCC2D9A595247| classic_bike|2022-03-28 11:35:53|2022-03-28 11:35:53|        Jersey & 3rd|           JC074|        Jersey & 3rd|         JC074| 40.72333158646436|-74.04595255851744| 40.72333158646436|-74.04595255851744|       casual|                0.0|              0.0|           0.0|          0.0|
|A37756EF50652802| classic_bike|2022-01-10 14:33:09|2022-01-10 14:33:09|        Brunswick St|           JC023|        Brunswick St|         JC023|        40.7241765|       -74.0506564|        40.7241765|       -74.0506564|       member|                0.0|              0.0|           0.0|          0.0|
|AD16901758C37664| classic_bike|2021-12-04 12:26:19|2021-12-04 12:26:19|Hoboken Terminal ...|           HB102|Hoboken Terminal ...|         HB102|  40.7360676564825|-74.02912706136703|  40.7360676564825|-74.02912706136703|       casual|                0.0|              0.0|           0.0|          0.0|
+----------------+-------------+-------------------+-------------------+--------------------+----------------+--------------------+--------------+------------------+------------------+------------------+------------------+-------------+-------------------+-----------------+--------------+-------------+
only showing top 20 rows

In [99]:
trips.sort(
    ["rideDurationMinutes", "rideDistanceKM"], ascending=[0, 0]
).show()  # 0, 0 means ascending = False - boolean

+----------------+-------------+-------------------+-------------------+--------------------+----------------+--------------------+--------------+---------+----------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+
|         ride_id|rideable_type|         started_at|           ended_at|  start_station_name|start_station_id|    end_station_name|end_station_id|start_lat| start_lng|          end_lat|           end_lng|member_casual|rideDurationMinutes|rideDurationHours|rideDistanceKM|rideDistanceM|
+----------------+-------------+-------------------+-------------------+--------------------+----------------+--------------------+--------------+---------+----------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+
|AFF1F450B44EF59E|  docked_bike|2021-07-31 19:36:50|2021-12-08 16:38:19|South Waterfront ...|           HB103|Grand Concourse &...|       8303.06|40.736982|-74.027781|        40.846221|        -73.909232|       casual|          187021.48|          3117.02|         15.72|      15720.0|
|C322C213579A803F|  docked_bike|2021-02-06 05:49:33|2021-05-21 15:27:44|     McGinley Square|           JC055|Bloomfield St & 1...|         HB203| 40.72534|-74.067622|         40.75453|         -74.02658|       casual|          150338.18|          2505.64|          4.74|       4740.0|
|6CEB3B83A5FBAF65|electric_bike|2021-06-12 20:37:07|2021-08-06 17:32:56|      Jackson Square|           JC063|Bergen Ave & Steg...|         JC108| 40.71113|  -74.0789|40.70657545063453| -74.0867006778717|       casual|           79015.82|          1316.93|          0.83|        830.0|
|67181F5C39DBDBFF|  docked_bike|2021-06-13 23:49:00|2021-07-31 15:11:57|    7 St & Monroe St|           HB304|W 147 St & Adam C...|       7971.07|40.746412|-74.037977|         40.82281|        -73.937413|       casual|           68602.95|          1143.38|         11.99|      11990.0|
|AF5746957A052C5A|  docked_bike|2021-06-06 12:18:03|2021-07-23 16:53:13|             Hilltop|           JC019|Bergen Ave & Steg...|         JC108|40.731168|-74.057573|40.70657545063453| -74.0867006778717|       casual|           67955.17|          1132.59|          3.67|       3670.0|
|01D7569FCD02C04F|  docked_bike|2021-09-26 12:00:53|2021-11-11 19:58:04|Columbus Park - C...|           HB501|   5 Corners Library|         JC018|40.748161|-74.032453|        40.734961|        -74.059503|       casual|           66717.18|          1111.95|          2.71|       2710.0|
|A066248051114D69|  docked_bike|2021-06-03 19:13:36|2021-07-04 02:09:22|9 St HBLR - Jacks...|           HB305|         Astor Place|         JC077|40.747907|-74.038411|40.71928220070702|-74.07126188278198|       casual|           43615.77|           726.93|          4.22|       4220.0|
|1C0893A074E6C870|  docked_bike|2021-04-24 14:02:52|2021-05-21 00:32:56|Hoboken Ave at Mo...|           JC105|Bloomfield St & 1...|         HB203|40.735208|-74.046964|         40.75453|         -74.02658|       casual|           38070.07|            634.5|          2.75|       2750.0|
|5B210F3FF6C038F3|  docked_bike|2021-06-18 14:06:41|2021-07-12 08:03:58|South Waterfront ...|           HB103|Frederick Douglas...|       7688.12|40.736982| -74.02778|        40.805159|        -73.954692|       casual|           34197.28|           569.95|          9.76|       9760.0|
|FEC2A78FD03ADDF1|  docked_bike|2021-10-25 16:12:28|2021-11-18 08:09:04|        Morris Canal|           JC072|    E 114 St & 1 Ave|       7540.02|40.712419|-74.038526|        40.794566|        -73.936254|       casual|            34076.6|           567.94|         12.56|      12560.0|
|E3C68E77202B45E6|  docked_bike|2021-03-27 14:54:00|2021-04-16 21:22:04|  Liberty Light Rail|           JC052|Westchester Ave &...|       8004.03|40.711242|-74.055701|        40.824956|        -73.891677|       casual|           29188.07|           486.47|         18.73|      18730.0|
|F72BFD1F68EA47AC|  docked_bike|2021-08-26 23:39:00|2021-09-15 20:04:43|12 St & Sinatra Dr N|           HB201|Church Sq Park - ...|         HB601|40.750604| -74.02402|        40.742659|        -74.032233|       casual|           28585.72|           476.43|          1.12|       1120.0|
|83DCB73B50AD617F|  docked_bike|2021-06-06 00:58:36|2021-06-25 21:03:03|       Grove St PATH|           JC005|Washington Pl & 6...|       5838.09|40.719586|-74.043117|      40.73224119|      -74.00026394|       casual|           28564.45|           476.07|          3.88|       3880.0|
|435CB0475E96C883|  docked_bike|2022-05-01 00:30:35|2022-05-20 20:12:05|South Waterfront ...|           HB103|      Lafayette Park|         JC078|40.736982|-74.027781|        40.713464|        -74.062859|       casual|            28541.5|           475.69|          3.95|       3950.0|
|4A116D956E092D28|  docked_bike|2022-07-10 14:05:49|2022-07-27 05:21:52|Hoboken Terminal ...|           HB101|     1 Ave & E 30 St|       6079.03|40.735938|-74.030305|        40.741444|        -73.975361|       casual|           23956.05|           399.27|          4.67|       4670.0|
|8204AAD5D7E50F8A|  docked_bike|2021-06-06 23:18:05|2021-06-22 02:41:16|South Waterfront ...|           HB103|     4 St & Grand St|         HB301|40.736982| -74.02778| 40.7422579775645|-74.03511106967926|       casual|           21803.18|           363.39|          0.85|        850.0|
|BD40D73F4134D242|  docked_bike|2022-07-05 16:09:31|2022-07-18 17:19:15|    Essex Light Rail|           JC038|9 St HBLR - Jacks...|         HB305|40.712774|-74.036486|        40.747907|        -74.038412|       casual|           18789.73|           313.16|          3.91|       3910.0|
|5234D881EC29D815|  docked_bike|2022-06-24 15:39:26|2022-07-07 06:52:57|      Pershing Field|           JC024|        Lincoln Park|         JC053|40.742677|-74.051789|        40.724605|        -74.078406|       casual|           18193.52|           303.23|          3.01|       3010.0|
|14A43A951176806C|  docked_bike|2021-02-03 14:28:31|2021-02-16 04:24:54|     Brunswick & 6th|           JC081|       Grove St PATH|         JC005|40.726012|-74.050389|        40.719586|        -74.043117|       member|           18116.38|           301.94|          0.94|        940.0|
|D5323843A85BFEC3|  docked_bike|2021-06-19 18:49:46|2021-07-01 17:46:29|      Lafayette Park|           JC078|   Madison St & 1 St|         HB402|40.713464|-74.062859|         40.73879|          -74.0393|       casual|           17216.72|           286.95|          3.45|       3450.0|
+----------------+-------------+-------------------+-------------------+--------------------+----------------+--------------------+--------------+---------+----------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+
only showing top 20 rows

In [100]:
trips.sort(["rideDurationMinutes", "rideDistanceKM"], ascending=[0, 1]).show()

+----------------+-------------+-------------------+-------------------+--------------------+----------------+--------------------+--------------+---------+----------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+
|         ride_id|rideable_type|         started_at|           ended_at|  start_station_name|start_station_id|    end_station_name|end_station_id|start_lat| start_lng|          end_lat|           end_lng|member_casual|rideDurationMinutes|rideDurationHours|rideDistanceKM|rideDistanceM|
+----------------+-------------+-------------------+-------------------+--------------------+----------------+--------------------+--------------+---------+----------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+
|AFF1F450B44EF59E|  docked_bike|2021-07-31 19:36:50|2021-12-08 16:38:19|South Waterfront ...|           HB103|Grand Concourse &...|       8303.06|40.736982|-74.027781|        40.846221|        -73.909232|       casual|          187021.48|          3117.02|         15.72|      15720.0|
|C322C213579A803F|  docked_bike|2021-02-06 05:49:33|2021-05-21 15:27:44|     McGinley Square|           JC055|Bloomfield St & 1...|         HB203| 40.72534|-74.067622|         40.75453|         -74.02658|       casual|          150338.18|          2505.64|          4.74|       4740.0|
|6CEB3B83A5FBAF65|electric_bike|2021-06-12 20:37:07|2021-08-06 17:32:56|      Jackson Square|           JC063|Bergen Ave & Steg...|         JC108| 40.71113|  -74.0789|40.70657545063453| -74.0867006778717|       casual|           79015.82|          1316.93|          0.83|        830.0|
|67181F5C39DBDBFF|  docked_bike|2021-06-13 23:49:00|2021-07-31 15:11:57|    7 St & Monroe St|           HB304|W 147 St & Adam C...|       7971.07|40.746412|-74.037977|         40.82281|        -73.937413|       casual|           68602.95|          1143.38|         11.99|      11990.0|
|AF5746957A052C5A|  docked_bike|2021-06-06 12:18:03|2021-07-23 16:53:13|             Hilltop|           JC019|Bergen Ave & Steg...|         JC108|40.731168|-74.057573|40.70657545063453| -74.0867006778717|       casual|           67955.17|          1132.59|          3.67|       3670.0|
|01D7569FCD02C04F|  docked_bike|2021-09-26 12:00:53|2021-11-11 19:58:04|Columbus Park - C...|           HB501|   5 Corners Library|         JC018|40.748161|-74.032453|        40.734961|        -74.059503|       casual|           66717.18|          1111.95|          2.71|       2710.0|
|A066248051114D69|  docked_bike|2021-06-03 19:13:36|2021-07-04 02:09:22|9 St HBLR - Jacks...|           HB305|         Astor Place|         JC077|40.747907|-74.038411|40.71928220070702|-74.07126188278198|       casual|           43615.77|           726.93|          4.22|       4220.0|
|1C0893A074E6C870|  docked_bike|2021-04-24 14:02:52|2021-05-21 00:32:56|Hoboken Ave at Mo...|           JC105|Bloomfield St & 1...|         HB203|40.735208|-74.046964|         40.75453|         -74.02658|       casual|           38070.07|            634.5|          2.75|       2750.0|
|5B210F3FF6C038F3|  docked_bike|2021-06-18 14:06:41|2021-07-12 08:03:58|South Waterfront ...|           HB103|Frederick Douglas...|       7688.12|40.736982| -74.02778|        40.805159|        -73.954692|       casual|           34197.28|           569.95|          9.76|       9760.0|
|FEC2A78FD03ADDF1|  docked_bike|2021-10-25 16:12:28|2021-11-18 08:09:04|        Morris Canal|           JC072|    E 114 St & 1 Ave|       7540.02|40.712419|-74.038526|        40.794566|        -73.936254|       casual|            34076.6|           567.94|         12.56|      12560.0|
|E3C68E77202B45E6|  docked_bike|2021-03-27 14:54:00|2021-04-16 21:22:04|  Liberty Light Rail|           JC052|Westchester Ave &...|       8004.03|40.711242|-74.055701|        40.824956|        -73.891677|       casual|           29188.07|           486.47|         18.73|      18730.0|
|F72BFD1F68EA47AC|  docked_bike|2021-08-26 23:39:00|2021-09-15 20:04:43|12 St & Sinatra Dr N|           HB201|Church Sq Park - ...|         HB601|40.750604| -74.02402|        40.742659|        -74.032233|       casual|           28585.72|           476.43|          1.12|       1120.0|
|83DCB73B50AD617F|  docked_bike|2021-06-06 00:58:36|2021-06-25 21:03:03|       Grove St PATH|           JC005|Washington Pl & 6...|       5838.09|40.719586|-74.043117|      40.73224119|      -74.00026394|       casual|           28564.45|           476.07|          3.88|       3880.0|
|435CB0475E96C883|  docked_bike|2022-05-01 00:30:35|2022-05-20 20:12:05|South Waterfront ...|           HB103|      Lafayette Park|         JC078|40.736982|-74.027781|        40.713464|        -74.062859|       casual|            28541.5|           475.69|          3.95|       3950.0|
|4A116D956E092D28|  docked_bike|2022-07-10 14:05:49|2022-07-27 05:21:52|Hoboken Terminal ...|           HB101|     1 Ave & E 30 St|       6079.03|40.735938|-74.030305|        40.741444|        -73.975361|       casual|           23956.05|           399.27|          4.67|       4670.0|
|8204AAD5D7E50F8A|  docked_bike|2021-06-06 23:18:05|2021-06-22 02:41:16|South Waterfront ...|           HB103|     4 St & Grand St|         HB301|40.736982| -74.02778| 40.7422579775645|-74.03511106967926|       casual|           21803.18|           363.39|          0.85|        850.0|
|BD40D73F4134D242|  docked_bike|2022-07-05 16:09:31|2022-07-18 17:19:15|    Essex Light Rail|           JC038|9 St HBLR - Jacks...|         HB305|40.712774|-74.036486|        40.747907|        -74.038412|       casual|           18789.73|           313.16|          3.91|       3910.0|
|5234D881EC29D815|  docked_bike|2022-06-24 15:39:26|2022-07-07 06:52:57|      Pershing Field|           JC024|        Lincoln Park|         JC053|40.742677|-74.051789|        40.724605|        -74.078406|       casual|           18193.52|           303.23|          3.01|       3010.0|
|14A43A951176806C|  docked_bike|2021-02-03 14:28:31|2021-02-16 04:24:54|     Brunswick & 6th|           JC081|       Grove St PATH|         JC005|40.726012|-74.050389|        40.719586|        -74.043117|       member|           18116.38|           301.94|          0.94|        940.0|
|D5323843A85BFEC3|  docked_bike|2021-06-19 18:49:46|2021-07-01 17:46:29|      Lafayette Park|           JC078|   Madison St & 1 St|         HB402|40.713464|-74.062859|         40.73879|          -74.0393|       casual|           17216.72|           286.95|          3.45|       3450.0|
+----------------+-------------+-------------------+-------------------+--------------------+----------------+--------------------+--------------+---------+----------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+
only showing top 20 rows

#### Limit

In PySpark, the `DataFrame.limit(num)` method restricts the result count of a DataFrame to a specified number of rows.

It is a __lazy transformation__, meaning that it does not immediately execute the operation but instead builds a logical plan that will be executed when an action is called such as `show()`, `collect()`, or `write()`.

In [101]:
trips.limit(10).show()

+----------------+-------------+--------------------+--------------------+--------------------+----------------+--------------------+--------------+-----------------+------------------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+
|         ride_id|rideable_type|          started_at|            ended_at|  start_station_name|start_station_id|    end_station_name|end_station_id|        start_lat|         start_lng|          end_lat|           end_lng|member_casual|rideDurationMinutes|rideDurationHours|rideDistanceKM|rideDistanceM|
+----------------+-------------+--------------------+--------------------+--------------------+----------------+--------------------+--------------+-----------------+------------------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+
|172DBBFC733F03CE|electric_bike|2024-10-10 14:54:...|2024-10-10 15:04:...|         Oakland Ave|           JC022|Stevens - River T...|         HB602|       40.7376037|       -74.0524783|40.74313282710551|-74.02698867022991|       member|               9.72|             0.16|          2.23|       2230.0|
|D20BBA4860FE736C|electric_bike|2024-10-03 19:20:...|2024-10-03 19:31:...|         Oakland Ave|           JC022|Stevens - River T...|         HB602|       40.7376037|       -74.0524783|40.74313282710551|-74.02698867022991|       casual|              11.42|             0.19|          2.23|       2230.0|
|86F89348995D0E6E| classic_bike|2024-10-20 12:14:...|2024-10-20 12:28:...|         Oakland Ave|           JC022|South Waterfront ...|         HB103|       40.7376037|       -74.0524783|40.73698221818716|-74.02778059244156|       casual|               13.6|             0.23|          2.08|       2080.0|
|AA55A717B7EC1D10| classic_bike|2024-10-20 14:40:...|2024-10-20 14:55:...|         Oakland Ave|           JC022|      Columbus Drive|         JC014|       40.7376037|       -74.0524783|40.71835519823214|-74.03891444206238|       member|               15.4|             0.26|          2.43|       2430.0|
|C72953D91E986DA7| classic_bike|2024-10-20 08:37:...|2024-10-20 08:42:...|     Brunswick & 6th|           JC081|       Washington St|         JC098|40.72601172964625|-74.05038893222809|       40.7242941|       -74.0354826|       member|               5.35|             0.09|          1.27|       1270.0|
|23A1827EA03A9AC2|electric_bike|2024-10-28 19:20:...|2024-10-28 19:25:...|         Oakland Ave|           JC022|Hoboken Ave at Mo...|         JC105|       40.7376037|       -74.0524783|40.73520838045357|-74.04696375131607|       member|                5.0|             0.08|          0.54|        540.0|
|6C0E882AE20AC640|electric_bike|2024-10-08 10:41:...|2024-10-08 10:44:...|      Pershing Field|           JC024| Leonard Gordon Park|         JC080|     40.742677141|     -74.051788633|40.74590996631558| -74.0572714805603|       member|               2.77|             0.05|          0.59|        590.0|
|FC4AEE485D39016D|electric_bike|2024-10-25 21:02:...|2024-10-25 21:11:...|      Pershing Field|           JC024| Leonard Gordon Park|         JC080|     40.742677141|     -74.051788633|40.74590996631558| -74.0572714805603|       member|               8.33|             0.14|          0.59|        590.0|
|3E4D96936A8660C6|electric_bike|2024-10-08 12:17:...|2024-10-08 12:20:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|                3.4|             0.06|          0.72|        720.0|
|9F2FBA8132468A3B|electric_bike|2024-10-28 11:00:...|2024-10-28 11:03:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|               2.53|             0.04|          0.72|        720.0|
+----------------+-------------+--------------------+--------------------+--------------------+----------------+--------------------+--------------+-----------------+------------------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+

#### .take()

This returns the first `n` rows of the DataFrame as a list of Row objects. It is an action that triggers the execution of the DataFrame transformations and returns the results to the driver program.

In [102]:
trips.take(5)

[Row(ride_id='172DBBFC733F03CE', rideable_type='electric_bike', started_at=datetime.datetime(2024, 10, 10, 14, 54, 24, 572000), ended_at=datetime.datetime(2024, 10, 10, 15, 4, 7, 657000), start_station_name='Oakland Ave', start_station_id='JC022', end_station_name='Stevens - River Ter & 6 St', end_station_id='HB602', start_lat=40.7376037, start_lng=-74.0524783, end_lat=40.74313282710551, end_lng=-74.02698867022991, member_casual='member', rideDurationMinutes=9.72, rideDurationHours=0.16, rideDistanceKM=2.23, rideDistanceM=2230.0),
 Row(ride_id='D20BBA4860FE736C', rideable_type='electric_bike', started_at=datetime.datetime(2024, 10, 3, 19, 20, 21, 215000), ended_at=datetime.datetime(2024, 10, 3, 19, 31, 46, 511000), start_station_name='Oakland Ave', start_station_id='JC022', end_station_name='Stevens - River Ter & 6 St', end_station_id='HB602', start_lat=40.7376037, start_lng=-74.0524783, end_lat=40.74313282710551, end_lng=-74.02698867022991, member_casual='casual', rideDurationMinutes=11.42, rideDurationHours=0.19, rideDistanceKM=2.23, rideDistanceM=2230.0),
 Row(ride_id='86F89348995D0E6E', rideable_type='classic_bike', started_at=datetime.datetime(2024, 10, 20, 12, 14, 56, 318000), ended_at=datetime.datetime(2024, 10, 20, 12, 28, 32, 53000), start_station_name='Oakland Ave', start_station_id='JC022', end_station_name='South Waterfront Walkway - Sinatra Dr & 1 St', end_station_id='HB103', start_lat=40.7376037, start_lng=-74.0524783, end_lat=40.73698221818716, end_lng=-74.02778059244156, member_casual='casual', rideDurationMinutes=13.6, rideDurationHours=0.23, rideDistanceKM=2.08, rideDistanceM=2080.0),
 Row(ride_id='AA55A717B7EC1D10', rideable_type='classic_bike', started_at=datetime.datetime(2024, 10, 20, 14, 40, 15, 227000), ended_at=datetime.datetime(2024, 10, 20, 14, 55, 39, 100000), start_station_name='Oakland Ave', start_station_id='JC022', end_station_name='Columbus Drive', end_station_id='JC014', start_lat=40.7376037, start_lng=-74.0524783, end_lat=40.71835519823214, end_lng=-74.03891444206238, member_casual='member', rideDurationMinutes=15.4, rideDurationHours=0.26, rideDistanceKM=2.43, rideDistanceM=2430.0),
 Row(ride_id='C72953D91E986DA7', rideable_type='classic_bike', started_at=datetime.datetime(2024, 10, 20, 8, 37, 3, 280000), ended_at=datetime.datetime(2024, 10, 20, 8, 42, 24, 770000), start_station_name='Brunswick & 6th', start_station_id='JC081', end_station_name='Washington St', end_station_id='JC098', start_lat=40.72601172964625, start_lng=-74.05038893222809, end_lat=40.7242941, end_lng=-74.0354826, member_casual='member', rideDurationMinutes=5.35, rideDurationHours=0.09, rideDistanceKM=1.27, rideDistanceM=1270.0)]

#### .show()

This method displays the top `n` rows of the DataFrame in a tabular format. It is an action that triggers the execution of the DataFrame transformations and returns the results to the driver program.

In [103]:
trips.show(5)

+----------------+-------------+--------------------+--------------------+------------------+----------------+--------------------+--------------+-----------------+------------------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+
|         ride_id|rideable_type|          started_at|            ended_at|start_station_name|start_station_id|    end_station_name|end_station_id|        start_lat|         start_lng|          end_lat|           end_lng|member_casual|rideDurationMinutes|rideDurationHours|rideDistanceKM|rideDistanceM|
+----------------+-------------+--------------------+--------------------+------------------+----------------+--------------------+--------------+-----------------+------------------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+
|172DBBFC733F03CE|electric_bike|2024-10-10 14:54:...|2024-10-10 15:04:...|       Oakland Ave|           JC022|Stevens - River T...|         HB602|       40.7376037|       -74.0524783|40.74313282710551|-74.02698867022991|       member|               9.72|             0.16|          2.23|       2230.0|
|D20BBA4860FE736C|electric_bike|2024-10-03 19:20:...|2024-10-03 19:31:...|       Oakland Ave|           JC022|Stevens - River T...|         HB602|       40.7376037|       -74.0524783|40.74313282710551|-74.02698867022991|       casual|              11.42|             0.19|          2.23|       2230.0|
|86F89348995D0E6E| classic_bike|2024-10-20 12:14:...|2024-10-20 12:28:...|       Oakland Ave|           JC022|South Waterfront ...|         HB103|       40.7376037|       -74.0524783|40.73698221818716|-74.02778059244156|       casual|               13.6|             0.23|          2.08|       2080.0|
|AA55A717B7EC1D10| classic_bike|2024-10-20 14:40:...|2024-10-20 14:55:...|       Oakland Ave|           JC022|      Columbus Drive|         JC014|       40.7376037|       -74.0524783|40.71835519823214|-74.03891444206238|       member|               15.4|             0.26|          2.43|       2430.0|
|C72953D91E986DA7| classic_bike|2024-10-20 08:37:...|2024-10-20 08:42:...|   Brunswick & 6th|           JC081|       Washington St|         JC098|40.72601172964625|-74.05038893222809|       40.7242941|       -74.0354826|       member|               5.35|             0.09|          1.27|       1270.0|
+----------------+-------------+--------------------+--------------------+------------------+----------------+--------------------+--------------+-----------------+------------------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+
only showing top 5 rows

#### .drop()

This method removes a specified column or multiple columns from the DataFrame. It is a transformation that returns a new DataFrame without the dropped column(s).

In [104]:
df_dropped1 = trips.drop(col("end_station_name"))

df_dropped1.show()

+----------------+-------------+--------------------+--------------------+--------------------+----------------+--------------+-----------------+------------------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+
|         ride_id|rideable_type|          started_at|            ended_at|  start_station_name|start_station_id|end_station_id|        start_lat|         start_lng|          end_lat|           end_lng|member_casual|rideDurationMinutes|rideDurationHours|rideDistanceKM|rideDistanceM|
+----------------+-------------+--------------------+--------------------+--------------------+----------------+--------------+-----------------+------------------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+
|172DBBFC733F03CE|electric_bike|2024-10-10 14:54:...|2024-10-10 15:04:...|         Oakland Ave|           JC022|         HB602|       40.7376037|       -74.0524783|40.74313282710551|-74.02698867022991|       member|               9.72|             0.16|          2.23|       2230.0|
|D20BBA4860FE736C|electric_bike|2024-10-03 19:20:...|2024-10-03 19:31:...|         Oakland Ave|           JC022|         HB602|       40.7376037|       -74.0524783|40.74313282710551|-74.02698867022991|       casual|              11.42|             0.19|          2.23|       2230.0|
|86F89348995D0E6E| classic_bike|2024-10-20 12:14:...|2024-10-20 12:28:...|         Oakland Ave|           JC022|         HB103|       40.7376037|       -74.0524783|40.73698221818716|-74.02778059244156|       casual|               13.6|             0.23|          2.08|       2080.0|
|AA55A717B7EC1D10| classic_bike|2024-10-20 14:40:...|2024-10-20 14:55:...|         Oakland Ave|           JC022|         JC014|       40.7376037|       -74.0524783|40.71835519823214|-74.03891444206238|       member|               15.4|             0.26|          2.43|       2430.0|
|C72953D91E986DA7| classic_bike|2024-10-20 08:37:...|2024-10-20 08:42:...|     Brunswick & 6th|           JC081|         JC098|40.72601172964625|-74.05038893222809|       40.7242941|       -74.0354826|       member|               5.35|             0.09|          1.27|       1270.0|
|23A1827EA03A9AC2|electric_bike|2024-10-28 19:20:...|2024-10-28 19:25:...|         Oakland Ave|           JC022|         JC105|       40.7376037|       -74.0524783|40.73520838045357|-74.04696375131607|       member|                5.0|             0.08|          0.54|        540.0|
|6C0E882AE20AC640|electric_bike|2024-10-08 10:41:...|2024-10-08 10:44:...|      Pershing Field|           JC024|         JC080|     40.742677141|     -74.051788633|40.74590996631558| -74.0572714805603|       member|               2.77|             0.05|          0.59|        590.0|
|FC4AEE485D39016D|electric_bike|2024-10-25 21:02:...|2024-10-25 21:11:...|      Pershing Field|           JC024|         JC080|     40.742677141|     -74.051788633|40.74590996631558| -74.0572714805603|       member|               8.33|             0.14|          0.59|        590.0|
|3E4D96936A8660C6|electric_bike|2024-10-08 12:17:...|2024-10-08 12:20:...|City Hall - Washi...|           HB105|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|                3.4|             0.06|          0.72|        720.0|
|9F2FBA8132468A3B|electric_bike|2024-10-28 11:00:...|2024-10-28 11:03:...|City Hall - Washi...|           HB105|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|               2.53|             0.04|          0.72|        720.0|
|B71B07C28733404F|electric_bike|2024-10-26 11:39:...|2024-10-26 11:45:...|City Hall - Washi...|           HB105|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|               6.08|              0.1|          0.72|        720.0|
|2EE1AB7AFEFB4CBB| classic_bike|2024-10-02 23:43:...|2024-10-02 23:47:...|City Hall - Washi...|           HB105|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|               3.72|             0.06|          0.72|        720.0|
|A7493DA7AFDDBC44| classic_bike|2024-10-12 12:48:...|2024-10-12 13:16:...|         Exchange Pl|           JC116|         HB602|40.71636596185077|  -74.034343957901|40.74313282710551|-74.02698867022991|       member|              27.62|             0.46|          3.04|       3040.0|
|7A956542D29EA30E| classic_bike|2024-10-24 17:48:...|2024-10-24 17:53:...|City Hall - Washi...|           HB105|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|               5.15|             0.09|          0.72|        720.0|
|157EFB12EA94DA9A|electric_bike|2024-10-02 14:37:...|2024-10-02 14:41:...|City Hall - Washi...|           HB105|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|               3.78|             0.06|          0.72|        720.0|
|3A54C7F77E03FB73| classic_bike|2024-10-06 01:42:...|2024-10-06 01:48:...|City Hall - Washi...|           HB105|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|               5.45|             0.09|          0.72|        720.0|
|94374385A5951BEE| classic_bike|2024-10-22 16:38:...|2024-10-22 16:45:...|City Hall - Washi...|           HB105|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|               6.52|             0.11|          0.72|        720.0|
|5E9040B2EF62AE11|electric_bike|2024-10-21 13:45:...|2024-10-21 13:57:...|      Pershing Field|           JC024|         HB602|     40.742677141|     -74.051788633|40.74313282710551|-74.02698867022991|       member|              11.17|             0.19|          2.09|       2090.0|
|99D204D580A9BD0C|electric_bike|2024-10-07 13:39:...|2024-10-07 13:48:...|      Pershing Field|           JC024|         HB602|     40.742677141|     -74.051788633|40.74313282710551|-74.02698867022991|       member|                9.3|             0.16|          2.09|       2090.0|
|7C3E2DA95C52FDFB|electric_bike|2024-10-03 08:52:...|2024-10-03 09:02:...|      Pershing Field|           JC024|         HB602|     40.742677141|     -74.051788633|40.74313282710551|-74.02698867022991|       member|               9.95|             0.17|          2.09|       2090.0|
+----------------+-------------+--------------------+--------------------+--------------------+----------------+--------------+-----------------+------------------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+
only showing top 20 rows

In [105]:
cols_to_drop = ["start_station_name", "end_station_name"]

df_dropped2 = trips.drop(*cols_to_drop)

df_dropped2.show()

+----------------+-------------+--------------------+--------------------+----------------+--------------+-----------------+------------------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+
|         ride_id|rideable_type|          started_at|            ended_at|start_station_id|end_station_id|        start_lat|         start_lng|          end_lat|           end_lng|member_casual|rideDurationMinutes|rideDurationHours|rideDistanceKM|rideDistanceM|
+----------------+-------------+--------------------+--------------------+----------------+--------------+-----------------+------------------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+
|172DBBFC733F03CE|electric_bike|2024-10-10 14:54:...|2024-10-10 15:04:...|           JC022|         HB602|       40.7376037|       -74.0524783|40.74313282710551|-74.02698867022991|       member|               9.72|             0.16|          2.23|       2230.0|
|D20BBA4860FE736C|electric_bike|2024-10-03 19:20:...|2024-10-03 19:31:...|           JC022|         HB602|       40.7376037|       -74.0524783|40.74313282710551|-74.02698867022991|       casual|              11.42|             0.19|          2.23|       2230.0|
|86F89348995D0E6E| classic_bike|2024-10-20 12:14:...|2024-10-20 12:28:...|           JC022|         HB103|       40.7376037|       -74.0524783|40.73698221818716|-74.02778059244156|       casual|               13.6|             0.23|          2.08|       2080.0|
|AA55A717B7EC1D10| classic_bike|2024-10-20 14:40:...|2024-10-20 14:55:...|           JC022|         JC014|       40.7376037|       -74.0524783|40.71835519823214|-74.03891444206238|       member|               15.4|             0.26|          2.43|       2430.0|
|C72953D91E986DA7| classic_bike|2024-10-20 08:37:...|2024-10-20 08:42:...|           JC081|         JC098|40.72601172964625|-74.05038893222809|       40.7242941|       -74.0354826|       member|               5.35|             0.09|          1.27|       1270.0|
|23A1827EA03A9AC2|electric_bike|2024-10-28 19:20:...|2024-10-28 19:25:...|           JC022|         JC105|       40.7376037|       -74.0524783|40.73520838045357|-74.04696375131607|       member|                5.0|             0.08|          0.54|        540.0|
|6C0E882AE20AC640|electric_bike|2024-10-08 10:41:...|2024-10-08 10:44:...|           JC024|         JC080|     40.742677141|     -74.051788633|40.74590996631558| -74.0572714805603|       member|               2.77|             0.05|          0.59|        590.0|
|FC4AEE485D39016D|electric_bike|2024-10-25 21:02:...|2024-10-25 21:11:...|           JC024|         JC080|     40.742677141|     -74.051788633|40.74590996631558| -74.0572714805603|       member|               8.33|             0.14|          0.59|        590.0|
|3E4D96936A8660C6|electric_bike|2024-10-08 12:17:...|2024-10-08 12:20:...|           HB105|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|                3.4|             0.06|          0.72|        720.0|
|9F2FBA8132468A3B|electric_bike|2024-10-28 11:00:...|2024-10-28 11:03:...|           HB105|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|               2.53|             0.04|          0.72|        720.0|
|B71B07C28733404F|electric_bike|2024-10-26 11:39:...|2024-10-26 11:45:...|           HB105|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|               6.08|              0.1|          0.72|        720.0|
|2EE1AB7AFEFB4CBB| classic_bike|2024-10-02 23:43:...|2024-10-02 23:47:...|           HB105|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|               3.72|             0.06|          0.72|        720.0|
|A7493DA7AFDDBC44| classic_bike|2024-10-12 12:48:...|2024-10-12 13:16:...|           JC116|         HB602|40.71636596185077|  -74.034343957901|40.74313282710551|-74.02698867022991|       member|              27.62|             0.46|          3.04|       3040.0|
|7A956542D29EA30E| classic_bike|2024-10-24 17:48:...|2024-10-24 17:53:...|           HB105|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|               5.15|             0.09|          0.72|        720.0|
|157EFB12EA94DA9A|electric_bike|2024-10-02 14:37:...|2024-10-02 14:41:...|           HB105|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|               3.78|             0.06|          0.72|        720.0|
|3A54C7F77E03FB73| classic_bike|2024-10-06 01:42:...|2024-10-06 01:48:...|           HB105|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|               5.45|             0.09|          0.72|        720.0|
|94374385A5951BEE| classic_bike|2024-10-22 16:38:...|2024-10-22 16:45:...|           HB105|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|               6.52|             0.11|          0.72|        720.0|
|5E9040B2EF62AE11|electric_bike|2024-10-21 13:45:...|2024-10-21 13:57:...|           JC024|         HB602|     40.742677141|     -74.051788633|40.74313282710551|-74.02698867022991|       member|              11.17|             0.19|          2.09|       2090.0|
|99D204D580A9BD0C|electric_bike|2024-10-07 13:39:...|2024-10-07 13:48:...|           JC024|         HB602|     40.742677141|     -74.051788633|40.74313282710551|-74.02698867022991|       member|                9.3|             0.16|          2.09|       2090.0|
|7C3E2DA95C52FDFB|electric_bike|2024-10-03 08:52:...|2024-10-03 09:02:...|           JC024|         HB602|     40.742677141|     -74.051788633|40.74313282710551|-74.02698867022991|       member|               9.95|             0.17|          2.09|       2090.0|
+----------------+-------------+--------------------+--------------------+----------------+--------------+-----------------+------------------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+
only showing top 20 rows

#### .dropDuplicates()

This method removes duplicate rows from the DataFrame based on all columns. It is a transformation that returns a new DataFrame without the duplicate rows.

In [106]:
trips_unique = trips.dropDuplicates()

print(f"Number of rides before: {trips.count()} | rides after: {trips_unique.count()}")

Number of rides before: 4689909 | rides after: 4689909

We can also drop duplicates based on a subset of columns by passing the column names as arguments to the `dropDuplicates()` method.

In [107]:
trips_unque2 = trips.dropDuplicates(["ride_id"])

print(f"Number of rides before: {trips.count()} | rides after: {trips_unque2.count()}")

Number of rides before: 4689909 | rides after: 4689886

In [108]:
trips.distinct().show()

+----------------+-------------+--------------------+--------------------+--------------------+----------------+--------------------+--------------+------------------+------------------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+
|         ride_id|rideable_type|          started_at|            ended_at|  start_station_name|start_station_id|    end_station_name|end_station_id|         start_lat|         start_lng|          end_lat|           end_lng|member_casual|rideDurationMinutes|rideDurationHours|rideDistanceKM|rideDistanceM|
+----------------+-------------+--------------------+--------------------+--------------------+----------------+--------------------+--------------+------------------+------------------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+
|C54B2D6A33C46C46|electric_bike|2024-10-22 17:21:...|2024-10-22 17:24:...|        Manila & 1st|           JC082|     Brunswick & 6th|         JC081|40.721650724879986|-74.04288411140442|40.72601172964625|-74.05038893222809|       member|               3.23|             0.05|           0.8|        800.0|
|AF7F10A1D6437C1A|electric_bike|2024-10-03 12:27:...|2024-10-03 12:31:...|         Exchange Pl|           JC116|           Warren St|         JC006| 40.71636596185077|  -74.034343957901|       40.7211236|      -74.03805095|       member|               3.87|             0.06|          0.61|        610.0|
|D21C4F93667679FB|electric_bike|2024-10-23 07:13:...|2024-10-23 07:18:...|      Pershing Field|           JC024|      Journal Square|         JC103|      40.742677141|     -74.051788633|         40.73367|          -74.0625|       member|               5.22|             0.09|          1.35|       1350.0|
|78EE14E6A3DAC86C| classic_bike|2024-10-07 18:16:...|2024-10-07 18:20:...|         Exchange Pl|           JC116|      Columbus Drive|         JC014| 40.71636596185077|  -74.034343957901|40.71835519823214|-74.03891444206238|       member|               4.35|             0.07|          0.44|        440.0|
|607A7CCFF19F6DDF| classic_bike|2024-10-29 10:58:...|2024-10-29 11:04:...|         Oakland Ave|           JC022|      Journal Square|         JC103|        40.7376037|       -74.0524783|         40.73367|          -74.0625|       member|               6.02|              0.1|          0.95|        950.0|
|8F47496C21C0B26D|electric_bike|2024-10-02 07:05:...|2024-10-02 07:12:...|      Pershing Field|           JC024|Hoboken Terminal ...|         HB102|      40.742677141|     -74.051788633| 40.7360676564825|-74.02912706136703|       member|               6.52|             0.11|          2.05|       2050.0|
|F3000767195650E9|electric_bike|2024-10-10 09:17:...|2024-10-10 09:23:...|       Washington St|           JC098|Hoboken Terminal ...|         HB102|        40.7242941|       -74.0354826| 40.7360676564825|-74.02912706136703|       member|               6.72|             0.11|          1.41|       1410.0|
|ACF9C083175F047B| classic_bike|2024-10-24 08:10:...|2024-10-24 08:16:...|       Hamilton Park|           JC009|Hoboken Ave at Mo...|         JC105|      40.727595966|     -74.044247311|40.73520838045357|-74.04696375131607|       member|               5.82|              0.1|          0.88|        880.0|
|0C8CC3438701545E|electric_bike|2024-10-07 15:52:...|2024-10-07 16:07:...|     Brunswick & 6th|           JC081|     Brunswick & 6th|         JC081| 40.72601172964625|-74.05038893222809|40.72601172964625|-74.05038893222809|       member|              15.03|             0.25|           0.0|          0.0|
|3D45FF223CD60171|electric_bike|2024-10-04 17:55:...|2024-10-04 18:07:...|         Exchange Pl|           JC116|     Jersey & 6th St|         JC027| 40.71636596185077|  -74.034343957901|40.72528910781132|-74.04557168483734|       member|              11.48|             0.19|          1.37|       1370.0|
|9844494444AE3E28| classic_bike|2024-10-23 12:51:...|2024-10-23 12:53:...|9 St HBLR - Jacks...|           HB305|  Madison St & 10 St|         HB503| 40.74790720968899|-74.03841152787209|40.74994325412246|-74.03586477041245|       member|               2.23|             0.04|          0.31|        310.0|
|555E279F4C4910F2|electric_bike|2024-10-26 15:11:...|2024-10-26 15:22:...|      Riverview Park|           JC057|Hoboken Terminal ...|         HB101|        40.7443187|       -74.0439909|40.73593758446329|-74.03030455112457|       member|               11.6|             0.19|          1.48|       1480.0|
|DAA942BC656D3BAB| classic_bike|2024-10-31 16:39:...|2024-10-31 16:43:...|9 St HBLR - Jacks...|           HB305|    Grand St & 14 St|         HB506| 40.74790720968899|-74.03841152787209|         40.75409|          -74.0316|       member|               3.62|             0.06|           0.9|        900.0|
|46B2DACED7E5F7E5|electric_bike|2024-10-20 15:14:...|2024-10-20 15:19:...|City Hall - Washi...|           HB105|  Marshall St & 2 St|         HB408|          40.73736|         -74.03097|        40.740802|        -74.042521|       casual|               5.53|             0.09|          1.05|       1050.0|
|CB7ABE12E29EE698| classic_bike|2024-10-23 16:52:...|2024-10-23 17:00:...|     McGinley Square|           JC055|Bergen Ave & Sip Ave|         JC109|  40.7253399253558|-74.06762212514877|40.73100888698729|-74.06443700194359|       member|               7.85|             0.13|          0.69|        690.0|
|F4CCFA090756916E| classic_bike|2024-10-21 17:55:...|2024-10-21 17:59:...|     McGinley Square|           JC055|Bergen Ave & Sip Ave|         JC109|  40.7253399253558|-74.06762212514877|40.73100888698729|-74.06443700194359|       member|               3.58|             0.06|          0.69|        690.0|
|D9BA93CE65449037| classic_bike|2024-10-12 13:41:...|2024-10-12 13:51:...|City Hall - Washi...|           HB105|      Pershing Field|         JC024|          40.73736|         -74.03097|     40.742677141|     -74.051788633|       member|              10.45|             0.17|          1.85|       1850.0|
|7F8B083B1A55F1ED|electric_bike|2024-10-16 08:24:...|2024-10-16 08:30:...|    Adams St & 12 St|           HB610|Hoboken Terminal ...|         HB102|40.751889392240685|-74.03329162748534| 40.7360676564825|-74.02912706136703|       member|               6.22|              0.1|          1.79|       1790.0|
|05F8C05384FAFCB4|electric_bike|2024-10-14 16:04:...|2024-10-14 16:08:...|City Hall - Washi...|           HB105|Mama Johnson Fiel...|         HB404|          40.73736|         -74.03097|40.74313993965626|-74.04004096984863|       casual|               4.52|             0.08|           1.0|       1000.0|
|A4710681DC1C36CE| classic_bike|2024-10-13 16:43:...|2024-10-13 17:07:...|     Brunswick & 6th|           JC081|        Newport Pkwy|         JC008| 40.72601172964625|-74.05038893222809|       40.7287448|       -74.0321082|       member|              23.35|             0.39|          1.57|       1570.0|
+----------------+-------------+--------------------+--------------------+--------------------+----------------+--------------------+--------------+------------------+------------------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+
only showing top 20 rows

#### Union & Union Byname

`Union` combines two DataFrames with the same schema into a single DataFrame, while `unionByName` allows for combining DataFrames with different schemas by matching columns by name.

The syntax for `union` is as follows:

```python
df1.union(df2)
```

The syntax for `unionByName` is as follows:

```python
df1.unionByName(df2)
```

In [109]:
data1 = [("1", "kad"), ("2", "gad")]

schema1 = """ id string, name string"""

df1 = spark.createDataFrame(data1, schema1)

data2 = [("3", "med"), ("4", "had")]

schema2 = """ id string, name string"""

df2 = spark.createDataFrame(data2, schema2)

In [110]:
df1.show()

+---+----+
| id|name|
+---+----+
|  1| kad|
|  2| gad|
+---+----+

In [111]:
df2.show()

+---+----+
| id|name|
+---+----+
|  3| med|
|  4| had|
+---+----+

In [112]:
df_combined = df1.union(df2)

df_combined.show()

+---+----+
| id|name|
+---+----+
|  1| kad|
|  2| gad|
|  3| med|
|  4| had|
+---+----+

In [113]:
data3 = [("kad", "1"), ("gad", "2")]

schema3 = """ name string, id string"""

df3 = spark.createDataFrame(data3, schema3)

df_combined_2 = df2.unionByName(df3)

df_combined_2.show()

+---+----+
| id|name|
+---+----+
|  3| med|
|  4| had|
|  1| kad|
|  2| gad|
+---+----+

### String Functions

Some commonly used string functions in PySpark include: `initcap()`, `lower()`, `upper()`, `ltrim()`, `rtrim()`, `trim()`, and `concat_ws()`.

#### initcap()
The `initcap()` function capitalizes the first letter of each word in a string column.

In [114]:
trips.select(initcap("start_station_name").alias("start_station_name")).show()

+--------------------+
|  start_station_name|
+--------------------+
|         Oakland Ave|
|         Oakland Ave|
|         Oakland Ave|
|         Oakland Ave|
|     Brunswick & 6th|
|         Oakland Ave|
|      Pershing Field|
|      Pershing Field|
|City Hall - Washi...|
|City Hall - Washi...|
|City Hall - Washi...|
|City Hall - Washi...|
|         Exchange Pl|
|City Hall - Washi...|
|City Hall - Washi...|
|City Hall - Washi...|
|City Hall - Washi...|
|      Pershing Field|
|      Pershing Field|
|      Pershing Field|
+--------------------+
only showing top 20 rows

#### lower()

The `lower()` function converts all characters in a string column to lowercase.

In [115]:
trips.select(lower("start_station_name").alias("start_station_name")).show()

+--------------------+
|  start_station_name|
+--------------------+
|         oakland ave|
|         oakland ave|
|         oakland ave|
|         oakland ave|
|     brunswick & 6th|
|         oakland ave|
|      pershing field|
|      pershing field|
|city hall - washi...|
|city hall - washi...|
|city hall - washi...|
|city hall - washi...|
|         exchange pl|
|city hall - washi...|
|city hall - washi...|
|city hall - washi...|
|city hall - washi...|
|      pershing field|
|      pershing field|
|      pershing field|
+--------------------+
only showing top 20 rows

### Date Functions

Some commonly used date functions in PySpark include: `current_date()`, `current_timestamp()`, `date_add()`, `date_sub()`, `datediff()`, and `months_between()`.

#### .current_date()

The `current_date()` function returns the current date as a column of type DateType.

In [116]:
trips_updated = trips.withColumn("current_date", current_date())

trips_updated.show(1)

+----------------+-------------+--------------------+--------------------+------------------+----------------+--------------------+--------------+----------+-----------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+------------+
|         ride_id|rideable_type|          started_at|            ended_at|start_station_name|start_station_id|    end_station_name|end_station_id| start_lat|  start_lng|          end_lat|           end_lng|member_casual|rideDurationMinutes|rideDurationHours|rideDistanceKM|rideDistanceM|current_date|
+----------------+-------------+--------------------+--------------------+------------------+----------------+--------------------+--------------+----------+-----------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+------------+
|172DBBFC733F03CE|electric_bike|2024-10-10 14:54:...|2024-10-10 15:04:...|       Oakland Ave|           JC022|Stevens - River T...|         HB602|40.7376037|-74.0524783|40.74313282710551|-74.02698867022991|       member|               9.72|             0.16|          2.23|       2230.0|  2026-07-02|
+----------------+-------------+--------------------+--------------------+------------------+----------------+--------------------+--------------+----------+-----------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+------------+
only showing top 1 row

#### date_add()

The `date_add()` function adds a specified number of days to a date column and returns the resulting date.

In [117]:
trips_updated = trips_updated.withColumn("future_date", date_add("current_date", 7))

trips_updated.show(5)

+----------------+-------------+--------------------+--------------------+------------------+----------------+--------------------+--------------+-----------------+------------------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+------------+-----------+
|         ride_id|rideable_type|          started_at|            ended_at|start_station_name|start_station_id|    end_station_name|end_station_id|        start_lat|         start_lng|          end_lat|           end_lng|member_casual|rideDurationMinutes|rideDurationHours|rideDistanceKM|rideDistanceM|current_date|future_date|
+----------------+-------------+--------------------+--------------------+------------------+----------------+--------------------+--------------+-----------------+------------------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+------------+-----------+
|172DBBFC733F03CE|electric_bike|2024-10-10 14:54:...|2024-10-10 15:04:...|       Oakland Ave|           JC022|Stevens - River T...|         HB602|       40.7376037|       -74.0524783|40.74313282710551|-74.02698867022991|       member|               9.72|             0.16|          2.23|       2230.0|  2026-07-02| 2026-07-09|
|D20BBA4860FE736C|electric_bike|2024-10-03 19:20:...|2024-10-03 19:31:...|       Oakland Ave|           JC022|Stevens - River T...|         HB602|       40.7376037|       -74.0524783|40.74313282710551|-74.02698867022991|       casual|              11.42|             0.19|          2.23|       2230.0|  2026-07-02| 2026-07-09|
|86F89348995D0E6E| classic_bike|2024-10-20 12:14:...|2024-10-20 12:28:...|       Oakland Ave|           JC022|South Waterfront ...|         HB103|       40.7376037|       -74.0524783|40.73698221818716|-74.02778059244156|       casual|               13.6|             0.23|          2.08|       2080.0|  2026-07-02| 2026-07-09|
|AA55A717B7EC1D10| classic_bike|2024-10-20 14:40:...|2024-10-20 14:55:...|       Oakland Ave|           JC022|      Columbus Drive|         JC014|       40.7376037|       -74.0524783|40.71835519823214|-74.03891444206238|       member|               15.4|             0.26|          2.43|       2430.0|  2026-07-02| 2026-07-09|
|C72953D91E986DA7| classic_bike|2024-10-20 08:37:...|2024-10-20 08:42:...|   Brunswick & 6th|           JC081|       Washington St|         JC098|40.72601172964625|-74.05038893222809|       40.7242941|       -74.0354826|       member|               5.35|             0.09|          1.27|       1270.0|  2026-07-02| 2026-07-09|
+----------------+-------------+--------------------+--------------------+------------------+----------------+--------------------+--------------+-----------------+------------------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+------------+-----------+
only showing top 5 rows

#### date_sub()

The `date_sub()` function subtracts a specified number of days from a date column and returns the resulting date.

In [118]:
trips_updated = trips_updated.withColumn("week_before", date_sub("current_date", 7))

trips_updated.show(5)

+----------------+-------------+--------------------+--------------------+------------------+----------------+--------------------+--------------+-----------------+------------------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+------------+-----------+-----------+
|         ride_id|rideable_type|          started_at|            ended_at|start_station_name|start_station_id|    end_station_name|end_station_id|        start_lat|         start_lng|          end_lat|           end_lng|member_casual|rideDurationMinutes|rideDurationHours|rideDistanceKM|rideDistanceM|current_date|future_date|week_before|
+----------------+-------------+--------------------+--------------------+------------------+----------------+--------------------+--------------+-----------------+------------------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+------------+-----------+-----------+
|172DBBFC733F03CE|electric_bike|2024-10-10 14:54:...|2024-10-10 15:04:...|       Oakland Ave|           JC022|Stevens - River T...|         HB602|       40.7376037|       -74.0524783|40.74313282710551|-74.02698867022991|       member|               9.72|             0.16|          2.23|       2230.0|  2026-07-02| 2026-07-09| 2026-06-25|
|D20BBA4860FE736C|electric_bike|2024-10-03 19:20:...|2024-10-03 19:31:...|       Oakland Ave|           JC022|Stevens - River T...|         HB602|       40.7376037|       -74.0524783|40.74313282710551|-74.02698867022991|       casual|              11.42|             0.19|          2.23|       2230.0|  2026-07-02| 2026-07-09| 2026-06-25|
|86F89348995D0E6E| classic_bike|2024-10-20 12:14:...|2024-10-20 12:28:...|       Oakland Ave|           JC022|South Waterfront ...|         HB103|       40.7376037|       -74.0524783|40.73698221818716|-74.02778059244156|       casual|               13.6|             0.23|          2.08|       2080.0|  2026-07-02| 2026-07-09| 2026-06-25|
|AA55A717B7EC1D10| classic_bike|2024-10-20 14:40:...|2024-10-20 14:55:...|       Oakland Ave|           JC022|      Columbus Drive|         JC014|       40.7376037|       -74.0524783|40.71835519823214|-74.03891444206238|       member|               15.4|             0.26|          2.43|       2430.0|  2026-07-02| 2026-07-09| 2026-06-25|
|C72953D91E986DA7| classic_bike|2024-10-20 08:37:...|2024-10-20 08:42:...|   Brunswick & 6th|           JC081|       Washington St|         JC098|40.72601172964625|-74.05038893222809|       40.7242941|       -74.0354826|       member|               5.35|             0.09|          1.27|       1270.0|  2026-07-02| 2026-07-09| 2026-06-25|
+----------------+-------------+--------------------+--------------------+------------------+----------------+--------------------+--------------+-----------------+------------------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+------------+-----------+-----------+
only showing top 5 rows

In [119]:
trips_updated = trips_updated.withColumn("week_before", date_add("current_date", -7))

trips_updated.show(5)

+----------------+-------------+--------------------+--------------------+------------------+----------------+--------------------+--------------+-----------------+------------------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+------------+-----------+-----------+
|         ride_id|rideable_type|          started_at|            ended_at|start_station_name|start_station_id|    end_station_name|end_station_id|        start_lat|         start_lng|          end_lat|           end_lng|member_casual|rideDurationMinutes|rideDurationHours|rideDistanceKM|rideDistanceM|current_date|future_date|week_before|
+----------------+-------------+--------------------+--------------------+------------------+----------------+--------------------+--------------+-----------------+------------------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+------------+-----------+-----------+
|172DBBFC733F03CE|electric_bike|2024-10-10 14:54:...|2024-10-10 15:04:...|       Oakland Ave|           JC022|Stevens - River T...|         HB602|       40.7376037|       -74.0524783|40.74313282710551|-74.02698867022991|       member|               9.72|             0.16|          2.23|       2230.0|  2026-07-02| 2026-07-09| 2026-06-25|
|D20BBA4860FE736C|electric_bike|2024-10-03 19:20:...|2024-10-03 19:31:...|       Oakland Ave|           JC022|Stevens - River T...|         HB602|       40.7376037|       -74.0524783|40.74313282710551|-74.02698867022991|       casual|              11.42|             0.19|          2.23|       2230.0|  2026-07-02| 2026-07-09| 2026-06-25|
|86F89348995D0E6E| classic_bike|2024-10-20 12:14:...|2024-10-20 12:28:...|       Oakland Ave|           JC022|South Waterfront ...|         HB103|       40.7376037|       -74.0524783|40.73698221818716|-74.02778059244156|       casual|               13.6|             0.23|          2.08|       2080.0|  2026-07-02| 2026-07-09| 2026-06-25|
|AA55A717B7EC1D10| classic_bike|2024-10-20 14:40:...|2024-10-20 14:55:...|       Oakland Ave|           JC022|      Columbus Drive|         JC014|       40.7376037|       -74.0524783|40.71835519823214|-74.03891444206238|       member|               15.4|             0.26|          2.43|       2430.0|  2026-07-02| 2026-07-09| 2026-06-25|
|C72953D91E986DA7| classic_bike|2024-10-20 08:37:...|2024-10-20 08:42:...|   Brunswick & 6th|           JC081|       Washington St|         JC098|40.72601172964625|-74.05038893222809|       40.7242941|       -74.0354826|       member|               5.35|             0.09|          1.27|       1270.0|  2026-07-02| 2026-07-09| 2026-06-25|
+----------------+-------------+--------------------+--------------------+------------------+----------------+--------------------+--------------+-----------------+------------------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+------------+-----------+-----------+
only showing top 5 rows

#### .datediff()

The `datediff()` function calculates the difference in days between two date columns and returns the result as an integer column.

In [120]:
trips_updated = trips_updated.withColumn(
    "days",
    date_diff("current_date", "week_before"),
)

trips_updated.show()

+----------------+-------------+--------------------+--------------------+--------------------+----------------+--------------------+--------------+-----------------+------------------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+------------+-----------+-----------+----+
|         ride_id|rideable_type|          started_at|            ended_at|  start_station_name|start_station_id|    end_station_name|end_station_id|        start_lat|         start_lng|          end_lat|           end_lng|member_casual|rideDurationMinutes|rideDurationHours|rideDistanceKM|rideDistanceM|current_date|future_date|week_before|days|
+----------------+-------------+--------------------+--------------------+--------------------+----------------+--------------------+--------------+-----------------+------------------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+------------+-----------+-----------+----+
|172DBBFC733F03CE|electric_bike|2024-10-10 14:54:...|2024-10-10 15:04:...|         Oakland Ave|           JC022|Stevens - River T...|         HB602|       40.7376037|       -74.0524783|40.74313282710551|-74.02698867022991|       member|               9.72|             0.16|          2.23|       2230.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|
|D20BBA4860FE736C|electric_bike|2024-10-03 19:20:...|2024-10-03 19:31:...|         Oakland Ave|           JC022|Stevens - River T...|         HB602|       40.7376037|       -74.0524783|40.74313282710551|-74.02698867022991|       casual|              11.42|             0.19|          2.23|       2230.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|
|86F89348995D0E6E| classic_bike|2024-10-20 12:14:...|2024-10-20 12:28:...|         Oakland Ave|           JC022|South Waterfront ...|         HB103|       40.7376037|       -74.0524783|40.73698221818716|-74.02778059244156|       casual|               13.6|             0.23|          2.08|       2080.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|
|AA55A717B7EC1D10| classic_bike|2024-10-20 14:40:...|2024-10-20 14:55:...|         Oakland Ave|           JC022|      Columbus Drive|         JC014|       40.7376037|       -74.0524783|40.71835519823214|-74.03891444206238|       member|               15.4|             0.26|          2.43|       2430.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|
|C72953D91E986DA7| classic_bike|2024-10-20 08:37:...|2024-10-20 08:42:...|     Brunswick & 6th|           JC081|       Washington St|         JC098|40.72601172964625|-74.05038893222809|       40.7242941|       -74.0354826|       member|               5.35|             0.09|          1.27|       1270.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|
|23A1827EA03A9AC2|electric_bike|2024-10-28 19:20:...|2024-10-28 19:25:...|         Oakland Ave|           JC022|Hoboken Ave at Mo...|         JC105|       40.7376037|       -74.0524783|40.73520838045357|-74.04696375131607|       member|                5.0|             0.08|          0.54|        540.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|
|6C0E882AE20AC640|electric_bike|2024-10-08 10:41:...|2024-10-08 10:44:...|      Pershing Field|           JC024| Leonard Gordon Park|         JC080|     40.742677141|     -74.051788633|40.74590996631558| -74.0572714805603|       member|               2.77|             0.05|          0.59|        590.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|
|FC4AEE485D39016D|electric_bike|2024-10-25 21:02:...|2024-10-25 21:11:...|      Pershing Field|           JC024| Leonard Gordon Park|         JC080|     40.742677141|     -74.051788633|40.74590996631558| -74.0572714805603|       member|               8.33|             0.14|          0.59|        590.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|
|3E4D96936A8660C6|electric_bike|2024-10-08 12:17:...|2024-10-08 12:20:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|                3.4|             0.06|          0.72|        720.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|
|9F2FBA8132468A3B|electric_bike|2024-10-28 11:00:...|2024-10-28 11:03:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|               2.53|             0.04|          0.72|        720.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|
|B71B07C28733404F|electric_bike|2024-10-26 11:39:...|2024-10-26 11:45:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|               6.08|              0.1|          0.72|        720.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|
|2EE1AB7AFEFB4CBB| classic_bike|2024-10-02 23:43:...|2024-10-02 23:47:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|               3.72|             0.06|          0.72|        720.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|
|A7493DA7AFDDBC44| classic_bike|2024-10-12 12:48:...|2024-10-12 13:16:...|         Exchange Pl|           JC116|Stevens - River T...|         HB602|40.71636596185077|  -74.034343957901|40.74313282710551|-74.02698867022991|       member|              27.62|             0.46|          3.04|       3040.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|
|7A956542D29EA30E| classic_bike|2024-10-24 17:48:...|2024-10-24 17:53:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|               5.15|             0.09|          0.72|        720.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|
|157EFB12EA94DA9A|electric_bike|2024-10-02 14:37:...|2024-10-02 14:41:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|               3.78|             0.06|          0.72|        720.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|
|3A54C7F77E03FB73| classic_bike|2024-10-06 01:42:...|2024-10-06 01:48:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|               5.45|             0.09|          0.72|        720.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|
|94374385A5951BEE| classic_bike|2024-10-22 16:38:...|2024-10-22 16:45:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|               6.52|             0.11|          0.72|        720.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|
|5E9040B2EF62AE11|electric_bike|2024-10-21 13:45:...|2024-10-21 13:57:...|      Pershing Field|           JC024|Stevens - River T...|         HB602|     40.742677141|     -74.051788633|40.74313282710551|-74.02698867022991|       member|              11.17|             0.19|          2.09|       2090.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|
|99D204D580A9BD0C|electric_bike|2024-10-07 13:39:...|2024-10-07 13:48:...|      Pershing Field|           JC024|Stevens - River T...|         HB602|     40.742677141|     -74.051788633|40.74313282710551|-74.02698867022991|       member|                9.3|             0.16|          2.09|       2090.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|
|7C3E2DA95C52FDFB|electric_bike|2024-10-03 08:52:...|2024-10-03 09:02:...|      Pershing Field|           JC024|Stevens - River T...|         HB602|     40.742677141|     -74.051788633|40.74313282710551|-74.02698867022991|       member|               9.95|             0.17|          2.09|       2090.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|
+----------------+-------------+--------------------+--------------------+--------------------+----------------+--------------------+--------------+-----------------+------------------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+------------+-----------+-----------+----+
only showing top 20 rows

#### .date_format()

In [ ]:
trips_updated = trips_updated.withColumn(
    "week_before", date_format("week_before", "dd-MM-yyyy")
)

trips_updated.show()

+----------------+-------------+--------------------+--------------------+--------------------+----------------+--------------------+--------------+-----------------+------------------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+------------+-----------+-----------+----+------------+
|         ride_id|rideable_type|          started_at|            ended_at|  start_station_name|start_station_id|    end_station_name|end_station_id|        start_lat|         start_lng|          end_lat|           end_lng|member_casual|rideDurationMinutes|rideDurationHours|rideDistanceKM|rideDistanceM|current_date|future_date|week_before|days|week_before_|
+----------------+-------------+--------------------+--------------------+--------------------+----------------+--------------------+--------------+-----------------+------------------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+------------+-----------+-----------+----+------------+
|172DBBFC733F03CE|electric_bike|2024-10-10 14:54:...|2024-10-10 15:04:...|         Oakland Ave|           JC022|Stevens - River T...|         HB602|       40.7376037|       -74.0524783|40.74313282710551|-74.02698867022991|       member|               9.72|             0.16|          2.23|       2230.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|  25-06-2026|
|D20BBA4860FE736C|electric_bike|2024-10-03 19:20:...|2024-10-03 19:31:...|         Oakland Ave|           JC022|Stevens - River T...|         HB602|       40.7376037|       -74.0524783|40.74313282710551|-74.02698867022991|       casual|              11.42|             0.19|          2.23|       2230.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|  25-06-2026|
|86F89348995D0E6E| classic_bike|2024-10-20 12:14:...|2024-10-20 12:28:...|         Oakland Ave|           JC022|South Waterfront ...|         HB103|       40.7376037|       -74.0524783|40.73698221818716|-74.02778059244156|       casual|               13.6|             0.23|          2.08|       2080.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|  25-06-2026|
|AA55A717B7EC1D10| classic_bike|2024-10-20 14:40:...|2024-10-20 14:55:...|         Oakland Ave|           JC022|      Columbus Drive|         JC014|       40.7376037|       -74.0524783|40.71835519823214|-74.03891444206238|       member|               15.4|             0.26|          2.43|       2430.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|  25-06-2026|
|C72953D91E986DA7| classic_bike|2024-10-20 08:37:...|2024-10-20 08:42:...|     Brunswick & 6th|           JC081|       Washington St|         JC098|40.72601172964625|-74.05038893222809|       40.7242941|       -74.0354826|       member|               5.35|             0.09|          1.27|       1270.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|  25-06-2026|
|23A1827EA03A9AC2|electric_bike|2024-10-28 19:20:...|2024-10-28 19:25:...|         Oakland Ave|           JC022|Hoboken Ave at Mo...|         JC105|       40.7376037|       -74.0524783|40.73520838045357|-74.04696375131607|       member|                5.0|             0.08|          0.54|        540.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|  25-06-2026|
|6C0E882AE20AC640|electric_bike|2024-10-08 10:41:...|2024-10-08 10:44:...|      Pershing Field|           JC024| Leonard Gordon Park|         JC080|     40.742677141|     -74.051788633|40.74590996631558| -74.0572714805603|       member|               2.77|             0.05|          0.59|        590.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|  25-06-2026|
|FC4AEE485D39016D|electric_bike|2024-10-25 21:02:...|2024-10-25 21:11:...|      Pershing Field|           JC024| Leonard Gordon Park|         JC080|     40.742677141|     -74.051788633|40.74590996631558| -74.0572714805603|       member|               8.33|             0.14|          0.59|        590.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|  25-06-2026|
|3E4D96936A8660C6|electric_bike|2024-10-08 12:17:...|2024-10-08 12:20:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|                3.4|             0.06|          0.72|        720.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|  25-06-2026|
|9F2FBA8132468A3B|electric_bike|2024-10-28 11:00:...|2024-10-28 11:03:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|               2.53|             0.04|          0.72|        720.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|  25-06-2026|
|B71B07C28733404F|electric_bike|2024-10-26 11:39:...|2024-10-26 11:45:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|               6.08|              0.1|          0.72|        720.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|  25-06-2026|
|2EE1AB7AFEFB4CBB| classic_bike|2024-10-02 23:43:...|2024-10-02 23:47:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|               3.72|             0.06|          0.72|        720.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|  25-06-2026|
|A7493DA7AFDDBC44| classic_bike|2024-10-12 12:48:...|2024-10-12 13:16:...|         Exchange Pl|           JC116|Stevens - River T...|         HB602|40.71636596185077|  -74.034343957901|40.74313282710551|-74.02698867022991|       member|              27.62|             0.46|          3.04|       3040.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|  25-06-2026|
|7A956542D29EA30E| classic_bike|2024-10-24 17:48:...|2024-10-24 17:53:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|               5.15|             0.09|          0.72|        720.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|  25-06-2026|
|157EFB12EA94DA9A|electric_bike|2024-10-02 14:37:...|2024-10-02 14:41:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|               3.78|             0.06|          0.72|        720.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|  25-06-2026|
|3A54C7F77E03FB73| classic_bike|2024-10-06 01:42:...|2024-10-06 01:48:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|               5.45|             0.09|          0.72|        720.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|  25-06-2026|
|94374385A5951BEE| classic_bike|2024-10-22 16:38:...|2024-10-22 16:45:...|City Hall - Washi...|           HB105|Stevens - River T...|         HB602|         40.73736|         -74.03097|40.74313282710551|-74.02698867022991|       member|               6.52|             0.11|          0.72|        720.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|  25-06-2026|
|5E9040B2EF62AE11|electric_bike|2024-10-21 13:45:...|2024-10-21 13:57:...|      Pershing Field|           JC024|Stevens - River T...|         HB602|     40.742677141|     -74.051788633|40.74313282710551|-74.02698867022991|       member|              11.17|             0.19|          2.09|       2090.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|  25-06-2026|
|99D204D580A9BD0C|electric_bike|2024-10-07 13:39:...|2024-10-07 13:48:...|      Pershing Field|           JC024|Stevens - River T...|         HB602|     40.742677141|     -74.051788633|40.74313282710551|-74.02698867022991|       member|                9.3|             0.16|          2.09|       2090.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|  25-06-2026|
|7C3E2DA95C52FDFB|electric_bike|2024-10-03 08:52:...|2024-10-03 09:02:...|      Pershing Field|           JC024|Stevens - River T...|         HB602|     40.742677141|     -74.051788633|40.74313282710551|-74.02698867022991|       member|               9.95|             0.17|          2.09|       2090.0|  2026-07-02| 2026-07-09| 2026-06-25|   7|  25-06-2026|
+----------------+-------------+--------------------+--------------------+--------------------+----------------+--------------------+--------------+-----------------+------------------+-----------------+------------------+-------------+-------------------+-----------------+--------------+-------------+------------+-----------+-----------+----+------------+
only showing top 20 rows


#### .fillna()

In [123]:
trips_updated.select(
    [count(when(col(c).isNull(), c)).alias(c) for c in trips_updated.columns]
).show()

+-------+-------------+----------+--------+------------------+----------------+----------------+--------------+---------+---------+-------+-------+-------------+-------------------+-----------------+--------------+-------------+------------+-----------+-----------+----+------------+
|ride_id|rideable_type|started_at|ended_at|start_station_name|start_station_id|end_station_name|end_station_id|start_lat|start_lng|end_lat|end_lng|member_casual|rideDurationMinutes|rideDurationHours|rideDistanceKM|rideDistanceM|current_date|future_date|week_before|days|week_before_|
+-------+-------------+----------+--------+------------------+----------------+----------------+--------------+---------+---------+-------+-------+-------------+-------------------+-----------------+--------------+-------------+------------+-----------+-----------+----+------------+
|      0|            0|         0|       0|               200|             200|            8379|          8813|        0|        0|      0|      0|            0|                  0|                0|             0|            0|           0|          0|          0|   0|           0|
+-------+-------------+----------+--------+------------------+----------------+----------------+--------------+---------+---------+-------+-------+-------------+-------------------+-----------------+--------------+-------------+------------+-----------+-----------+----+------------+

There are no missing values in the DataFrame, so the `fillna()` function is not applicable in this case.

However, we can use the `fillna()` function to fill missing values in a DataFrame with a specified value. For example, we can fill all null values in a column with a default value or fill null values in multiple columns with different default values.

```python
df.fillna({'column1': 'default_value1', 'column2': 'default_value2'})
```

Or, to the entire DataFrame with a single value:

```python
df.fillna('default_value')
```

### Split & Indexing

Split and Indexing are common operations in PySpark for manipulating string columns and accessing specific elements within them. The `split()` function can be used to split a string column into an array of substrings based on a specified delimiter. 

After splitting, you can use indexing to access specific elements of the resulting array.

The syntax for the `split()` function is as follows:

```python
from pyspark.sql.functions import split

df.withColumn('new_column', split(df['string_column'], 'delimiter'))
```